class NewSouthWales {
  static List<String> cities = [
  'Sydney',
  'Newcastle',
  'Wollongong',
  'Central Coast',
  'Maitland',
  'Tweed Heads',
  'Wagga Wagga',
  'Albury',
  'Coffs Harbour',
  'Tamworth',
  'Orange',
  'Dubbo',
  'Queanbeyan',
  'Nowra-Bomaderry',
  'Bathurst',
  'Lismore',
  'Gosford',
  'Armidale',
  'Taree',
  ' Griffith',
  'Broken Hill',
  'Ballina',
  'Port Macquarie',
  'Goulburn',
  'Cessnock',
  'Moruya',
  'Ulladulla',
  'Forster-Tuncurry',
  'Muswellbrook',
  'Parkes',
  'Nelson Bay',
  'Bowral-Mittagong',
  'Blue Mountains',
  'Singleton',
  'Cooma',
  'Narrabri',
  'Windsor',
  'Kiama',
  'Inverell',
  'Batemans Bay',
  'Cowra',
  'Young',
  'Byron Bay',
  'Cootamundra',
  'Narromine',
  'Merimbula',
  'Scone',
  'Yass',
  'Tumut',
  'Junee',
  'Gunnedah',
  'Moree',
  'Manilla',
  'Mudgee',
  'Grong Grong',
  'Tenterfield',
  'Bombala',
  'Hay',
  'Deniliquin',
  'Warren',
  'Nyngan',
  'Wilcannia',
  'Barham',
  'Finley',
  'Jerilderie',
  'Corowa',
  'Jerangle',
  'Khancoban',
  'Dorrigo',
  'Wauchope',
  'South West Rocks',
  'Harden',
  'Boorowa',
  'Cudal',
  'Kurri Kurri',
  'Portland',
  'Lithgow',
  'Yamba',
  'Eden',
  'Dalmeny',
  'Bega',
  'Kempsey',
  'Tumbarumba',
  'Rylstone',
  'Nimmitabel',
  'Braidwood',
  'Culcairn',
  'Stockinbingal',
  'Berry',
  'Kangaroo Valley',
  'Bellingen',
  'Bulahdelah',
  'Milton',
  'Laurieton',
  'Gerringong',
  'Bungendore',
  'Grenfell',
  'Coonabarabran',
  'Nambucca Heads',
  'Tocumwal',
  'Coraki',
  'Woodburn',
  'Maclean',
  'Krambach',
  'Kangaroo Island',
  'Tennant Creek',
  'Alice Springs',
  'Katherine',
  'Yulara',
  'Wagin',
  'Broomehill',
  'Kojonup',
  'Manjimup',
  'Pemberton',
  'Northam',
  'York',
  'Moora',
  'Merredin',
  'Esperance',
  'Ravensthorpe',
  'Katanning',
  'Mount Barker',
  'Bridgetown',
  'Narrogin',
  'Gnowangerup',
  'Jerramungup',
  'Wickham',
  'Roebourne',
  'Carnarvon',
  'Exmouth',
  'Denham',
  'Onslow',
  'Tom Price',
  'Newman',
  'Meekatharra',
  'Wiluna',
  'Leinster',
  'Leonora',
  'Laverton',
  'Kalgoorlie',
  'Coolgardie',
  'Norseman',
  'Kondinin',
  'Kukerin',
  'Lake Grace',
  'Hyden',
  'Hopetoun',
  'Bullfinch',
  'Southern Cross',
  'Yalgoo',
  'Mount Magnet',
  'Cue',
  'Sandstone',
  'Kalgoorlie-Boulder',
  'Wickham',
  'Halls Creek',
  'Port Hedland',
  'South Hedland',
  'Karratha',
  'Dampier',
  'Roebourne',
  'Point Samson',
  'Cossack',
  'Pannawonica',
  'Paraburdoo',
  'Tom Price',
  'Wittenoom',
  'Marble Bar',
  'Nullagine',
  'Onslow',
  'Exmouth',
  'Coral Bay',
  'Carnarvon',
  'Shark Bay',
  'Denham',
  'Monkey Mia',
  'Kalbarri',
  'Jurien Bay',
  'Cervantes',
  'Green Head',
  'Leeman',
  'Dongara',
  'Port Denison',
  'Geraldton',
  'Northampton',
  'Kalbarri',
  'Horrocks',
  'Mullewa',
  'Three Springs',
  'Perenjori',
  ];
}

class Victoria {
  static List<String> cities = [
    'Melbourne',
    'Geelong',
    'Ballarat',
    'Bendigo',
    'Shepparton',
    'Melton',
    'Mildura',
    'Warrnambool',
    'Sunbury',
    'Traralgon',
    'Wangaratta',
    'Echuca',
    'Morwell',
    'Warragul',
    'Colac',
    'Sale',
    'Horsham',
    'Ocean Grove',
    'Bacchus Marsh',
    'Torquay',
    'Cranbourne',
    'Bairnsdale',
    'Drouin',
    'Moe',
    'Benalla',
    'Portland',
    'Hamilton',
    'Yarrawonga',
    'Leopold',
    'Seymour',
    'Maryborough',
    'Stawell',
    'Kyabram',
    'Ararat',
    'Castlemaine',
    'Gisborne',
    'Lara',
    'Cobram',
    'Churchill',
    'Kyneton',
    'Healesville',
    'Swan Hill',
    'Daylesford',
    'Tatura',
    'Port Fairy',
    'Mount Eliza',
    'Bunyip',
    'Nagambie',
    'Bacchus Marsh',
    'Mansfield',
    'Yarra Junction',
    'Lorne',
    'Sorrento',
    'Yallourn North',
    'Lakes Entrance',
    'Heyfield',
    'Maffra',
    'Rutherglen',
    'Euroa',
    'Inverloch',
    'Wonthaggi',
    'Sebastopol',
    'Corowa',
    'Red Cliffs',
    'Warracknabeal',
    'Heathcote',
    'Tallangatta',
    'Dookie',
    'Nathalia',
    'Trafalgar',
    'Violet Town',
    'Wodonga',
    'Ararat',
    'St Arnaud',
    'Eaglehawk',
    'Bright',
    'Yarra Glen',
    'Dunkeld',
    'Porepunkah',
    'Bannockburn',
    'Camperdown',
    'Tongala',
    'Woodend',
    'Maldon',
    'Casterton',
    'Hastings',
    'Kerang',
    'Elmore',
    'Heathcote',
    'Stratford',
    'Eildon',
    'Trentham',
    'Mooroopna',
    'Wunghnu',
    'Rochester',
    'Edenhope',
    'Avoca',
    'Wallan',
    'Tatura',
    'Nyora',
    'Inglewood',
    'Wedderburn',
    'Beechworth',
    'Myrtleford',
    'Bright',
    'Wangaratta',
    'Leongatha',
    'Beech Forest',
    'Timboon',
    'Lavers Hill',
    'Derrinallum',
    'Skipton',
    'Beaufort',
    'Clunes',
    'Wandong',
    'Lancefield',
    'Kilmore',
    'Inverleigh',
    'Cressy',
    'Lismore',
    'Scarsdale',
    'Ballan',
    'Lismore',
    'Skipton',
    'Harcourt',
    'Elphinstone',
    'Mount Macedon',
    'Monegeetta',
    'Yarragon',
    'Stratford',
    'Metung',
    'Swan Reach',
    'Tooradin',
    'Warburton',
    'Heathcote',
    'Stanley',
    'Woodend',
    'Trentham',
    'Yea',
    'Beechworth',
    'Wandin East',
    'Kooweerup',
    'Wattle Glen',
    'Nar Nar Goon',
    'Heathcote',
    'Winchelsea',
    'Lorne',
    'Corindhap',
    'Forrest',
    'Gellibrand',
    'Falls Creek',
    'Mount Beauty',
    'Bonnie Doon',
    'Stratford',
    'Lakes Entrance',
    'Lorne',
    'Wilsons Promontory',
    'Halls Gap',
    'Traralgon',
    'Fish Creek',
    'Glenrowan',
    'Beechworth',
    'Walhalla',
    'Mount Buller',
    'Mansfield',
    'Falls Creek',
    'Beechworth',
    'Corryong',
    'Omeo',
    'Mount Beauty',
    'Mansfield',
    'Lake Bolac',
    'Moe',
    'Buchan',
    'Jindivick',
    'Koo Wee Rup',
    'Dandenong',
    'Chelsea',
    'Noble Park',
    'Mulgrave',
    'Croydon',
    'Ringwood',
    'Doncaster',
    'Eltham',
    'Greensborough',
    'Kilmore',
    'Whittlesea',
    'Wallan',
    'Laverton',
    'Sunshine',
    'Werribee',
    'Williamstown',
    'Altona',
    'Footscray',
    'Yarraville',
    'Spotswood',
    'South Melbourne',
    'Albert Park',
    'Port Melbourne',
    'St Kilda',
    'Elwood',
    'Middle Park',
    'Docklands',
    'Southbank',
    'Melbourne CBD',
    'East Melbourne',
    'Carlton',
    'Parkville',
    'North Melbourne',
    'West Melbourne',
    'Kensington',
    'Flemington',
    'Moonee Ponds',
    'Essendon',
    'Ascot Vale',
    'Maribyrnong',
    'Keilor',
    'Tullamarine',
    'Niddrie',
    'Strathmore',
    'Airport West',
    'Glenroy',
    'Broadmeadows',
    'Sunbury',
    'Craigieburn',
    'Roxburgh Park',
    'Meadow Heights',
    'Gladstone Park',
    'Keilor',
    'St Albans',
    'Deer Park',
    'Taylors Lakes',
    'Sydenham',
    'Caroline Springs',
    'Albanvale',
    'Sunshine West',
    'Derrimut',
    'Brooklyn',
    'Braybrook',
    'Yarraville',
    'Footscray',
    'Seddon',
    'Kingsville',
    'Tottenham',
    'West Footscray',
    'Spotswood',
    'Newport',
    'Williamstown',
    'Altona',
    'Seaholme',
    'Brooklyn',
    'Yarraville',
    'Footscray'
  ];
}
class Queensland {
  static List<String> cities = [
  'Brisbane',
  'Gold Coast',
  'Sunshine Coast',
  'Townsville',
  'Cairns',
  'Toowoomba',
  'Mackay',
  'Rockhampton',
  'Bundaberg',
  'Hervey Bay',
  'Gladstone',
  'Maryborough',
  'Mount Isa',
  'Gympie',
  'Nambour',
  'Yeppoon',
  'Warwick',
  'Emerald',
  'Dalby',
  'Charters Towers',
  'Weipa',
  'Innisfail',
  'Moranbah',
  'Ayr',
  'Atherton',
  'Kingaroy',
  'Tully',
  'Bowen',
  'Goondiwindi',
  'Tamborine Mountain',
  'Blackwater',
  'Stanthorpe',
  'Hughenden',
  'Collinsville',
  'Home Hill',
  'Sarina',
  'Maleny',
  'Barcaldine',
  'Kilcoy',
  'Childers',
  'Gayndah',
  'Longreach',
  'Cooktown',
  'Roma',
  'Chinchilla',
  'Augathella',
  'Tara',
  'Beaudesert',
  'Clermont',
  'Charleville',
  'St George',
  'Biloela',
  'Blackall',
  'Ingham',
  'Monto',
  'Millmerran',
  'Allora',
  'Cunnamulla',
  'Ilfracombe',
  'Herberton',
  'Windorah',
  'Winton',
  'Eulo',
  'Camooweal',
  'Wondai',
  'Kilkivan',
  'Theodore',
  'Monto',
  'Cloncurry',
  'Normanton',
  'Richmond',
  'Georgetown',
  'Baralaba',
  'Surat',
  'Capella',
  'Tambo',
  'Quilpie',
  'Thargomindah',
  'Camooweal',
  'Doomadgee',
  'Karumba',
  'Normanton',
  'Burketown',
  'Dajarra',
  'Yarrabah',
  'Mornington Island',
  'Palm Island',
  'Woorabinda',
  'Pormpuraaw',
  'Kowanyama',
  'Doomadgee',
  'Kowanyama',
  'Coen',
  'Hope Vale',
  'Aurukun',
  ];
}

class WesternAustralia {
  static List<String> cities = [
    'Perth',
    'Mandurah',
    'Bunbury',
    'Geraldton',
    'Albany',
    'Kalgoorlie-Boulder',
    'Rockingham',
    'Busselton',
    'Karratha',
    'Broome',
    'Port Hedland',
    'South Hedland',
    'Dampier',
    'Tom Price',
    'Esperance',
    'Carnarvon',
    'Exmouth',
    'Onslow',
    'Newman',
    'Meekatharra',
    'Leinster',
    'Leonora',
    'Laverton',
    'Coolgardie',
    'Norseman',
    'Kondinin',
    'Kukerin',
    'Lake Grace',
    'Hyden',
    'Hopetoun',
    'Bullfinch',
    'Southern Cross',
    'Yalgoo',
    'Mount Magnet',
    'Cue',
    'Sandstone',
    'Wickham',
    'Roebourne',
    'Point Samson',
    'Cossack',
    'Pannawonica',
    'Paraburdoo',
    'Wittenoom',
    'Marble Bar',
    'Nullagine',
    'Coral Bay',
    'Shark Bay',
    'Monkey Mia',
    'Kalbarri',
    'Jurien Bay',
    'Cervantes',
    'Green Head',
    'Leeman',
    'Dongara',
    'Geraldton',
    'Northampton',
    'Horrocks',
    'Mullewa',
    'Three Springs',
    'Perenjori',
    'Carnamah',
  ];
}

class SouthAustralia {
  static List<String> cities = [
    'Adelaide',
    'Mount Gambier',
    'Whyalla',
    'Murray Bridge',
    'Port Lincoln',
    'Port Augusta',
    'Port Pirie',
    'Gawler',
    'Glenelg',
    'Morphett Vale',
    'Victor Harbor',
    'Renmark',
    'Tanunda',
    'Kadina',
    'Nuriootpa',
    'Berri',
    'Goolwa',
    'Angaston',
    'Strathalbyn',
    'Kapunda',
    'Millicent',
    'Loxton',
    'Peterborough',
    'Naracoorte',
    'Streaky Bay',
    'Ceduna',
    'Barmera',
    'Meningie',
    'Kimba',
    'Port Broughton',
    'Jamestown',
    'Moonta',
    'Keith',
    'Bordertown',
    'Port Vincent',
    'Tumby Bay',
    'Kingston SE',
    'Penola',
    'Lucindale',
    'Wallaroo',
    'Beachport',
    'Strathmerton',
    'Woomera',
    'Coober Pedy',
    'Kimba',
    'Tintinara',
    'Waikerie',
    'Robe',
    'Port Pirie South',
    'Port Augusta West',
    'Port Augusta North',
    'Port Augusta East',
    'Port Adelaide',
    'Whyalla Norrie',
    'Whyalla Jenkins',
    'Whyalla Stuart',
    'Whyalla Playford',
    'Whyalla',
    'Warradale',
    'Victor Harbor',
    'Unley',
    'Torrens Park',
    'Tumby Bay',
    'Two Wells',
    'Truro',
    'Trott Park',
    'Trihi',
    'Tranmere',
    'Totness',
    'Tongala',
    'Todmorden',
    'Tintinara',
    'Tiddy Widdy Beach',
    'Thorngate',
    'Thevenard',
    'Thebarton',
    'Tepko',
    'Telowie',
    'Taylorville',
    'Tarlee',
    'Taplan',
    'Tantanoola',
    'Tantanoola',
    'Tamboon',
    'Taldra',
    'Tailem Bend',
    'Tabourie Lake',
    'Sydenham',
  ];
}

class TasmaniaState {
  static List<String> cities = [
    'Hobart',
    'Launceston',
    'Devonport',
    'Burnie',
    'Ulverstone',
    'Kingston',
    'Queenstown',
  ];
}