class FederationOfBosniaAndHerzegovina {
  static List<String> cities = <String>[
    'Sarajevo',
    'Zenica',
    'Tuzla',
    'Mostar',
    'Bihac',
    'Banja Luka',
    'Travnik',
    'Doboj',
    'Livno',
    'Brcko',
    'Cazin',
    'Gorazde',
    'Gracanica',
    'Siroki Brijeg',
    'Konjic',
    'Bosanska Krupa',
    'Srebrenik',
    'Visoko',
    'Capljina',
    'Tesanj',
    'Zavidovici',
    'Sanski Most',
    'Ljubuski',
    'Bugojno',
    'Novi Travnik',
    'Derventa',
    'Odzak',
    'Tomislavgrad',
    'Fojnica',
    'Gornji Vakuf',
    'Trn',
    'Kakanj',
    'Kljuc',
    'Grude',
    'Bosanska Dubica',
    'Vitez',
    'Jajce',
    'Lukavac',
    'Donji Vakuf',
    'Zepce',
    'Bosanska Gradiska',
    'Celinac',
    'Zivinice',
    'Prozor',
    'Kalesija',
    'Kupres',
    'Buzim',
    'Zepce',
    'Bosanska Gradiska',
    'Celinac',
    'Zivinice',
    'Prozor',
    'Kalesija',
    'Kupres',
    'Buzim',
  ];
}

class RepublikaSrpska {
  static List<String> cities = <String>[
    'East Sarajevo',
    'Bijeljina',
    'Trebinje',
    'Prijedor',
    'Doboj',
    'Zvornik',
    'Brod',
    'Mrkonjic Grad',
    'Foca',
    'Visegrad',
    'Modrica',
    'Laktasi',
    'Gracanica',
    'Berkovici',
    'Ljubinje',
    'Kostajnica',
    'Kozarska Dubica',
    'Pale',
    'Srbac',
    'Vlasenica',
    'Prnjavor',
    'Kotor Varos',
    'Teslic',
    'Sokolac',
    'Teslic',
    'Sokolac',
  ];
}


class BrckoDistrictCities {
  static List<String> cities = [
    'Brčko',
    'Bijeljina',
    'Gračanica',
    'Srebrenik',
    'Odžak',
    'Šamac',
  ];
}
