
class BlagoevgradProvince {
  static List<String> cities = <String>[
    'Blagoevgrad',
    'Petrich',
    'Gotse Delchev',
    'Sandanski',
    'Razlog',
    'Bansko',
    'Simitli',
    'Malko Tarnovo',
    'Kresna',
    'Belitsa',
    'Strumyani',
    'Garmen',
    'Kulinoto',
    'Rila',
    'Yakoruda',
  ];
}

class BurgasProvince {
  static List<String> cities = <String>[
    'Burgas',
    'Sunny Beach',
    'Nesebar',
    'Pomorie',
    'Sveti Vlas',
    'Sozopol',
    'Primorsko',
    'Ahtopol',
    'Karnobat',
    'Tsarevo',
    'Kameno',
    'Sredets',
    'Obzor',
    'Aheloy',
    'Kiten',
    'Ruen',
  ];
}

class DobrichProvince {
  static List<String> cities = <String>[
    'Dobrich',
    'Balchik',
    'Shabla',
    'Kavarna',
    'Tervel',
    'General Toshevo',
    'Dobrichka',
    'Krushari',
    'Bozhurets',
    'Obrochishte',
    'Durankulak',
    'Albena',
    'Kamen Bryag',
    'Balgarevo',
    'Krapets',
    'Tyulenovo',
  ];
}

class GabrovoProvince {
  static List<String> cities = <String>[
    'Gabrovo',
    'Sevlievo',
    'Tryavna',
    'Dryanovo',
    'Apriltsi',
    'Plachkovtsi',
    'Ugarchin',
    'Bozhentsi',
    'Shipka',
    'Chervena Lokva',
    'Gorsko Slivovo',
    'Pchelishte',
    'Gradishte',
  ];
}

class HaskovoProvince {
  static List<String> cities = <String>[
    'Haskovo',
    'Dimitrovgrad',
    'Harmanli',
    'Svilengrad',
    'Lyubimets',
    'Topolovgrad',
    'Simeonovgrad',
    'Ivaylovgrad',
    'Madzharovo',
    'Stambolovo',
    'Sveti Nikole',
    'Merichleri',
    'Oryncho',
    'Generalovo',
    'Klokotnitsa',
    'Ustrem',
    'Dryanovo',
    'Polkovnik Serafimovo',
  ];
}

class KardzhaliProvince {
  static List<String> cities = <String>[
    'Kardzhali',
    'Krumovgrad',
    'Momchilgrad',
    'Ardino',
    'Dzhebel',
    'Kirkovo',
    'Madzharovo',
    'Chernoochene',
    'Cherniche',
    'Malko Tarnovo',
    'Bivolyane',
    'Enina',
    'Glavan',
    'Doganovo',
    'Gorno Dryanovo',
    'Mogilitsa',
    'Oreshets',
    'Zvezdelina',
  ];
}

class KyustendilProvince {
  static List<String> cities = <String>[
    'Kyustendil',
    'Dupnitsa',
    'Kocherinovo',
    'Boboshevo',
    'Sapareva Banya',
    'Berkovitsa',
    'Rila',
    'Radomir',
    'Bobov Dol',
    'Nevestino',
    'Treshtenik',
    'Osogovo',
    'Dragichevo',
    'Zemen',
    'Gorno Kraishte',
    'Tsrancha',
    'Sklave',
    'Tataritsa',
    'Dolna Nevestino',
    'Malo Buchino',
    'Gorna Grashtica',
    'Ovchartsi',
    'Gabrovitsa',
    'Chiflik',
    'Makedonski Brod',
    'Cherni Vrah',
    'Nevestino',
    'Treshtenik',
    'Osogovo',
    'Dragichevo',
    'Zemen',
    'Gorno Kraishte',
    'Tsrancha',
    'Sklave',
    'Tataritsa',
    'Dolna Nevestino',
    'Malo Buchino',
    'Gorna Grashtica',
    'Ovchartsi',
    'Gabrovitsa',
    'Chiflik',
    'Makedonski Brod',
    'Cherni Vrah',
  ];
}

class LovechProvince {
  static List<String> cities = <String>[
  'Lovech',
  'Troyan',
  'Pavel Banya',
  'Apriltsi',
  'Letnitsa',
  'Lukovit',
  'Yablanitsa',
  'Teteven',
  'Ugarchin',
  'Sevlievo',
  'Belene',
  'Shipkovo',
  'Belitsa',
  ];
}

class MontanaProvince {
  static List<String> cities = <String>[
    'Montana',
    'Berkovitsa',
    'Lom',
    'Valchedram',
    'Varshets',
    'Boychinovtsi',
    'Brusartsi',
    'Chiprovtsi',
    'Georgi Damyanovo',
    'Kozi Rog',
    'Valchedram',
    'Borovtsi',
    'Draganovtsi',
    'Gaganitsa',
    'Glavan',
    'Lilyach',
    'Medkovets',
    'Oreshets',
    'Podgorets',
    'Rebrovo',
    'Selanovtsi',
    'Smolyanets',
    'Stanevtsi',
    'Stoyanovo',
    'Tsvetkova Bara',
    'Tsvetovo',
  ];
}

class PazardzhikProvince {
  static List<String> cities = <String>[
    'Pazardzhik',
    'Velingrad',
    'Septemvri',
    'Batak',
    'Panagyurishte',
    'Rakitovo',
    'Batak',
    'Brezovo',
    'Lesichovo',
    'Strelcha',
    'Saedinenie',
    'Belovo',
    'Peshtera',
    'Kostandovo',
    'Varvara',
    'Vetren',
    'Razlog',
    'Bratanitsa',
    'Boikovo',
    'Beguntsi',
    'Simeonovo',
    'Yabulkovets',
  ];
}

class PernikProvince {
  static List<String> cities = <String>[
    'Pernik',
    'Radomir',
    'Breznik',
    'Tran',
    'Kovachevtsi',
    'Studena',
    'Batanovtsi',
    'Berende',
    'Brezovets',
    'Bukovets',
    'Chepintsi',
    'Daskalovo',
    'Debeli Lag',
    'Dragichevo',
    'Dren',
    'Golemo Buchino',
    'Golyamo Belovo',
    'Gradets',
    'Ivan Vazovo',
    'Klisura',
    'Krakra',
    'Kriva Bara',
    'Levski',
    'Leskovets',
    'Nikopol',
    'Ostrets',
    'Podgorets',
    'Polikraishte',
    'Rakovski',
    'Rudartsi',
    'Skrino',
    'Slatina',
    'Sotirya',
    'Stara Krepost',
    'Starosel',
    'Topolnitsa',
    'Tsarevets',
    'Vlado Trichkov',
    'Vrachesh',
    'Yasenovets',
  ];
}

class PlevenProvince {
  static List<String> cities = <String>[
    'Pleven',
    'Pordim',
    'Dolna Mitropolia',
    'Nikopol',
    'Levski',
    'Cherven Bryag',
    'Belene',
    'Gulyantsi',
    'Dolna Mitropolia',
    'Nikopol',
    'Levski',
    'Cherven Bryag',
    'Belene',
    'Gulyantsi',
    'Dolna Mitropolia',
    'Nikopol',
    'Levski',
    'Cherven Bryag',
    'Belene',
    'Gulyantsi',
    'Dolna Mitropolia',
    'Nikopol',
    'Levski',
    'Cherven Bryag',
    'Belene',
    'Gulyantsi',
    'Dolna Mitropolia',
    'Nikopol',
    'Levski',
    'Cherven Bryag',
    'Belene',
    'Gulyantsi',
  ];
}

class PlovdivProvince {
  static List<String> cities = <String>[
    'Plovdiv',
    'Asenovgrad',
    'Pazardzhik',
    'Stara Zagora',
    'Karlovo',
    'Hissarya',
    'Rakovski',
    'Chirpan',
    'Parvomay',
    'Rakovski',
    'Sadovo',
    'Rakovski',
    'Sadovo',
    'Banya',
    'Rozovo',
    'Perushtitsa',
    'Sadovo',
    'Kaloyanovo',
    'Sadovo',
    'Kuklen',
    'Sadovo',
    'Kuklen',
  ];
}

class RazgradProvince {
  static List<String> cities = <String>[
  'Razgrad',
  'Isperih',
  'Kubrat',
  'Zavet',
  'Samuil',
  'Loznitsa',
  'Tsar Kaloyan',
  'Senovo',
  'Samuilovo',
  'Zavet',
  'Bogomilovo',
  'Krivina',
  'Mirovets',
  'Vetrintsi',
  'Glavinitsa',
  'Dve Mogili',
  'Tsar Kaloyan',
  'Senovo',
  'Samuilovo',
  'Zavet',
  'Bogomilovo',
  'Krivina',
  'Mirovets',
  'VVetrintsi',
    'Glavinitsa',
    'Dve Mogili',
  ];
}

class RuseProvince {
  static List<String> cities = <String>[
    'Ruse',
    'Byala',
    'Borovo',
    'Dve Mogili',
    'Ivanovo',
    'Slivo Pole',
    'Tutrakan',
    'Vetovo',
    'Svishtov',
  ];
}

class ShumenProvince {
  static List<String> cities = <String>[
    'Shumen',
    'Novi Pazar',
    'Veliki Preslav',
    'Smyadovo',
    'Kaspichan',
    'Varbitsa',
    'Kaolinovo',
    'Hitrino',
    'Shumen',
    'Novi Pazar',
    'Veliki Preslav',
    'Smyadovo',
    'Kaspichan',
    'Varbitsa',
    'Kaolinovo',
    'Hitrino',
  ];
}

class SilistraProvince {
  static List<String> cities = <String>[
    'Silistra',
    'Dulovo',
    'Glavinitsa',
    'Tutrakan',
    'Alfatar',
    'Sredec',
    'Kaynardzha',
    'Spartak',
    'Zornitsa',
    'Drinovo',
    'Dobrina',
    'Kochovo',
    'Loznitsa',
    'Vetren',
    'Malak Preslavets',
    'Padina',
    'Pisanets',
    'Sarnevo',
    'Sarnino',
    'Sennik',
    'Sinagovtsi',
    'Sladun',
    'Staro selo',
    'Strazhitsa',
    'Strelkovo',
    'Tsar Kaloyan',
    'Vasil Levski',
    'Yarebitsa',
  ];
}

class SlivenProvince {
  static List<String> cities = <String>[
    'Sliven',
    'Kotel',
    'Tvarditsa',
    'Nova Zagora',
    'Zheravna',
    'Kermen',
    'Sinitevo',
    'Bryagovo',
    'Svetlina',
    'Bryastovo',
    'Trakiets',
    'Veliko Tarnovo',
    'Sborishte',
    'Kolyu Ganchevo',
    'Banya',
    'Dimitrovche',
    'Malko Chochoveni',
    'Slivnitsa',
    'Sokolovo',
    'Sredets',
    'Zornitsa',
  ];
}

class SmolyanProvince {
  static List<String> cities = <String>[
    'Smolyan',
    'Chepelare',
    'Rudozem',
    'Madan',
    'Dospat',
    'Borino',
    'Mugla',
    'Dunevo',
    'Momchilovtsi',
    'Shiroka Laka',
    'Stoykite',
    'Pamporovo',
    'Mugla',
    'Dunevo',
    'Momchilovtsi',
    'Shiroka Laka',
    'Stoykite',
    'Pamporovo',
  ];
}

class SofiaProvince {
  static List<String> cities = <String>[
    'Sofia',
    'Pernik',
    'Dupnitsa',
    'Kyustendil',
    'Botevgrad',
    'Radomir',
    'Samokov',
    'Kostenets',
    'Svoge',
    'Elin Pelin',
    'Godech',
    'Kostinbrod',
    'Ihtiman',
    'Slivnitsa',
    'Dragoman',
    'Berkovitsa',
    'Mirkovo',
    'Dolna Banya',
    'Govedartsi',
    'Zlatitsa',
    'Bojurishte',
    'Gorna Malina',
    'Anton',
    'Mirkovo',
    'Dolna Banya',
    'Govedartsi',
    'Zlatitsa',
    'Bojurishte',
    'Gorna Malina',
    'Anton',
  ];
}

class StaraZagoraProvince {
  static List<String> cities = <String>[
    'Stara Zagora',
    'Kazanlak',
    'Chirpan',
    'Radnevo',
    'Galabovo',
    'Nedelino',
    'Opan',
    'Svilengrad',
    'Topolovgrad',
    'Karlovo',
    'Simeonovgrad',
    'Stara Rechka',
    'Rozovo',
    'Malko Yovo',
    'Opan',
    'Svilengrad',
    'Topolovgrad',
    'Karlovo',
    'Simeonovgrad',
    'Stara Rechka',
    'Rozovo',
    'Malko Yovo',
  ];
}

class TargovishteProvince {
  static List<String> cities = <String>[
    'Targovishte',
    'Omurtag',
    'Popovo',
    'Antonovo',
    'Opaka',
    'Gorna Kremena',
    'Zheravitsa',
    'Beli Plast',
    'Pobeda',
    'Medovo',
    'Bozhevets',
    'Koznitsa',
    'Opan',
    'Bakadzhik',
    'Blagoevo',
    'Yasenovets',
    'Lozenets',
    'Stoyan Mihaylovski',
    'Golyamo Novo',
    'Slomer',
  ];
}

class VarnaProvince {
  static List<String> cities = <String>[
  'Varna',
  'Devnya',
  'Provadiya',
  'Aksakovo',
  'Beloslav',
  'Byala',
  'Dalgopol',
  'Dolni Chiflik',
  'Dolni Dabnik',
    'Isperikh',
    'Kavarna',
    'Novi Pazar',
    'Suvorovo',
    'Valchi Dol',
    'Vetrino',
    'Vulchi Dol',
    'Vakarel',
    'Slanchevo',
    'Krushari',
    'Konstantinovo',
    'Bolyartsi',
    'Osenovo',
    'Staro Oryahovo',
    'Balik',
    'Dracevo',
    'Kranevo',
    'Zvezditsa',
    'Konstantinovo',
    'Bolyartsi',
    'Osenovo',
    'Staro Oryahovo',
    'Balik',
    'Dracevo',
    'Kranevo',
    'Zvezditsa',
  ];
}

class VelikoTarnovoProvince {
  static List<String> cities = <String>[
    'Veliko Tarnovo',
    'Gorna Oryahovitsa',
    'Svishtov',
    'Suhindol',
    'Zlataritsa',
    'Lyaskovets',
    'Strazhitsa',
    'Pavlikeni',
    'Elena',
    'Elena',
    'Gorna Oryahovitsa',
    'Svishtov',
    'Suhindol',
    'Zlataritsa',
    'Lyaskovets',
    'Strazhitsa',
    'Pavlikeni',
    'Elena',
  ];
}

class VidinProvince {
  static List<String> cities = <String>[
    'Vidin',
    'Belogradchik',
    'Dryanovo',
    'Kula',
    'Bregovo',
    'Boynitsa',
    'Dimovo',
    'Gramada',
    'Novo Selo',
    'Novo Selo',
    'Belogradchik',
    'Dryanovo',
    'Kula',
    'Bregovo',
    'Boynitsa',
    'Dimovo',
    'Gramada',
    'Novo Selo',
    'Novo Selo',
  ];
}

class VratsaProvince {
  static List<String> cities = <String>[
    'Vratsa',
    'Mezdra',
    'Kozloduy',
    'Kriva Palanka',
    'Borovan',
    'Oryahovo',
    'Yablanitsa',
    'Hayredin',
    'Borovan',
    'Oryahovo',
    'Yablanitsa',
    'Hayredin',
    'Borovan',
    'Oryahovo',
    'Yablanitsa',
    'Hayredin',
  ];
}

class YambolProvince {
  static List<String> cities = <String>[
    'Yambol',
    'Elhovo',
    'Straldzha',
    'Tundzha',
    'Tenevo',
    'Topolovgrad',
    'Kermen',
    'Glavinitsa',
    'Kirilovo',
    'Bolyarovo',
    'Boyanovo',
    'Lyubenovo',
    'Kabile',
    'Voden',
    'Poda',
    'Kabile',
    'Voden',
    'Poda',
  ];
}



