class IcelandicRegions {
  static List<String> capitalRegionCities = [
  'Reykjavík',
  'Kópavogur',
  'Hafnarfjörður',
  'Garðabær',
  'Mosfellsbær',
  'Seltjarnarnes',
  'Álftanes',
  'Hafnir',
  'Reykjanesbær',
  'Grindavík',
  'Sandgerði',
  'Njarðvík',
  'Vogar',
  'Hvalsneskirkja',
  'Þorlákshöfn',
  'Eyrarbakki',
  'Stokkseyri',
  'Hveragerði',
  'Selfoss',
  'Hveragerði',
  'Þorlákshöfn',
  'Hveragerði',
  'Stokkseyri',
  'Laugarvatn',
  'Flúðir',
  'Reykholt',
  'Arborg',
  'Borganes',
  'Stykkishólmur',
  'Hellissandur',
  'Ólafsvík',
  'Grundarfjörður',
  'Snæfellsbær',
  'Dalabyggð',
  'Búðardalur',
  'Reykhólar',
  'Tálknafjörður',
  'Patreksfjörður',
  'Bíldudalur',
  'Tingeyri',
  'Ísafjörður',
  'Hornstrandir',
  'Drangsnes',
  'Bolungarvík',
  'Súðavík',
  'Flateyri',
  'Suðureyri',
  'Ísafjörður',
  'Hnífsdalur',
  'Bíldudalur',
  'Patreksfjörður',
  'Tálknafjörður',
  'Látrabjarg',
  'Rauðisandur',
  'Breiðavík',
  'Reykhólar',
  'Bíldudalur',
  'Tingeyri',
  'Þingeyri',
  'Hrafnseyri',
  'Bolungarvík',
  'Suðureyri',
  'Ísafjörður',
  'Flateyri',
  'Súðavík',
  'Hnífsdalur',
  'Hornstrandir',
  'Norðurfjörður',
  'Suðureyri',
  'Bolungarvík',
  'Ísafjörður',
  'Tálknafjörður',
  'Patreksfjörður',
  'Bíldudalur',
  'Tingeyri',
  'Drangsnes',
  'Árneshreppur',
  'Kaldrananeshreppur',
  'Strandabyggð',
  'Reykhólahreppur',
  'Tálknafjarðarhreppur',
  'Tingeyrarhreppur',
  'Þingeyjarsveit',
  'Þingeyri',
  'Ísafjarðarbær',
  'Patreksfjörður',
  'Vesturbyggð',
  'Vesturbyggð',
  'Bolungarvík',
  'Ísafjörður',
  'Suðureyri',
  'Flateyri',
  'Súðavík',
  'Bíldudalur',
  'Reykhólahreppur',
  'Tálknafjarðarhreppur',
  'Tingeyrarhreppur',
  'Strandabyggð',
  'Kaldrananeshreppur',
  'Árneshreppur',
  'Drangsnes',
  'Reykhólar',
  'Breiðavík',
  'Rauðisandur',
  'Látrabjarg',
  'Tálknafjarðarhreppur',
  'Tingeyrarhreppur',
  'Reykhólahreppur',
  'Strandabyggð',
  'Vesturbyggð',
  'Ísafjarðarbær',
  'Sveitarfélagið Árneshreppur',
  'Vesturbyggð',
  'Strandabyggð',
  'Bolungarvík',
  'Ísafjörður',
  'Súðavík',
  'Flateyri',
  'Suðureyri',
  'Ísafjörður',
  'Bolungarvík',
  'Bíldudalur',
  'Tálknafjörður',
  'Patreksfjörður',
  'Tingeyri',
  'Þingeyri',
  'Þingeyjarsveit',
  'Tálknafjarðarhreppur',
  'Reykhólahreppur',
  'Drangsnes',
  'Árneshreppur',
  'Kaldrananeshreppur',
  'Breiðavík',
  'Rauðisandur',
  'Látrabjarg',
  'Strandabyggð',
  'Reykhólahreppur',
  'Tingeyrarhreppur',
  'Tálknafjarðarhreppur',
  'Vesturbyggð',
  'Sveitarfélagið Árneshreppur',
  'Ísafjarðarbær',
  'Vesturbyggð',
  'Strandabyggð',
  'Bolungarvík',
  'Ísafjörður',
  'Súðavík',
  'Flateyri',
  'Suðureyri',
  'Ísafjörður',
  'Bolungarvík',
  'Bíldudalur',
  'Tálknafjörður',
  'Patreksfjörður',
  'Tingeyri',
  'Þingeyri',
  'Þingeyjarsveit',
  'Tálknafjarðarhreppur',
  'Reykhólahreppur',
  'Drangsnes',
  'Árneshreppur',
  'Kaldrananeshreppur',
  'Breiðavík',
  'Rauðisandur',

];

  static List<String> southernPeninsulaCities = [
    'Keflavík',
    'Reykjanesbær',
    'Grindavík',
    'Sandgerði',
    'Njarðvík',
    'Vogar',
    'Hvalsneskirkja',
    'Þorlákshöfn',
    'Eyrarbakki',
    'Stokkseyri',
    'Hveragerði',
    'Selfoss',
    'Hveragerði',
    'Þorlákshöfn',
    'Hveragerði',
    'Stokkseyri',
    'Laugarvatn',
    'Flúðir',
    'Reykholt',
    'Arborg',
    // Additional cities and towns
  ];

  static List<String> westernRegionCities = [
    'Akranes',
    'Borgarnes',
    'Stykkishólmur',
    'Ólafsvík',
    'Hvanneyri',
    // Additional cities and towns
  ];

  static List<String> westfjordsCities = [
    'Ísafjörður',
    'Patreksfjörður',
    'Bolungarvík',
    // Additional cities and towns
  ];

  static List<String> northwestCities = [
    'Sauðárkrókur',
    'Blönduós',
    'Hvammstangi',
    // Additional cities and towns
  ];

  static List<String> northeastCities = [
    'Akureyri',
    'Húsavík',
    'Svalbarðseyri',
    // Additional cities and towns
  ];

  static List<String> eastCities = [
    'Egilsstaðir',
    'Seyðisfjörður',
    'Vopnafjörður',
    // Additional cities and towns
  ];

  static List<String> southCities = [
    'Selfoss',
    'Hella',
    'Vík í Mýrdal',
    'Hveragerði',
    'Þorlákshöfn',
    // Additional cities and towns
  ];
}
