class AndamanAndNicobarIslands {
  static List<String> cities = [
    "Port Blair",
    "Car Nicobar",
    "Bombooflat",
    "Garacharma",
    "Mayabunder",
    "Diglipur",
    "Port Blair",
    "Rangat",
    "Mayabunder",
    "Ferrargunj",
    "Hut Bay",
    "Garacharma",
    "Port Blair",
    "Diglipur",
    "Bombooflat",
    "Car Nicobar",
    "Bombooflat",
    "Garacharma",
    "Mayabunder",
    "Diglipur",
    "Port Blair",
    "Rangat",
    "Mayabunder",
    "Ferrargunj",
    "Hut Bay",
    "Garacharma",
    "Port Blair",
    "Diglipur",
    "Bombooflat",
    "Car Nicobar",
  ];
}

class AndhraPradesh {
  static List<String> cities = [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kakinada",
    "Anantapur",
    "Kadapa",
    "Vizianagaram",
    "Eluru",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Proddatur",
    "Chittoor",
    "Hindupur",
    "Bhimavaram",
    "Madanapalle",
    "Guntakal",
    "Srikakulam",
    "Dharmavaram",
    "Gudivada",
    "Narasaraopet",
    "Tadipatri",
    "Tadepalligudem",
    "Amaravati",
    "Chilakaluripet",
    "Puttur",
    "Anakapalle",
    "Jaggaiahpet",
    "Bobbili",
    "Ponnur",
    "Samalkot",
    "Vinukonda",
    "Araku Valley",
    "Pithapuram",
    "Repalle",
    "Nidadavole",
    "Sattenapalle",
    "Peddapuram",
    "Ramachandrapuram",
    "Bapatla",
    "Parvathipuram",
    "Macherla",
    "Salur",
    "Punganur",
    "Markapur",
    "Kandukur",
    "Narsipatnam",
    "Tuni",
    "Tenali",
    "Rayachoti",
    "Kadiri",
    "Srikalahasti",
    "Bheemunipatnam",
    "Venkatagiri",
    "Nagari",
    "Gooty",
    "Dharmavaram",
    "Pulivendula",
    "Penukonda",
    "Amalapuram",
    "Palakollu",
    "Bellampalle",
    "Sullurpeta",
    "Tadepalligudem",
    "Jammalamadugu",
    "Adoni",
    "Rayadurg",
    "Narasapuram",
    "Renigunta",
    "Kavali",
    "Srikakulam",
    "Punganur",
    "Vikarabad",
    "Mandapeta",
    "Tadepalle",
    "Palasa Kasibugga",
    "Nuzvid",
    "Uravakonda",
    "Narsipatnam",
    "Sadasivpet",
    "Yellandu",
    "Pedana",
    "Naidupet",
    "Venkatagiri",
    "Bobbili",
    "Markapur",
    "Kandukur",
    "Ramachandrapuram",
    "Addanki",
    "Jaggaiahpet",
    "Nidadavole",
    "Vizianagaram",
    "Pitapuram",
    "Pulivendla",
    "Giddalur",
    "Venkatagiri",
    "Palwancha",
    "Punganur",
    "Gudur",
    "Mandamarri",
    "Tadipatri",
    "Venkatagiri",
    "Macherla",
    "Mandapeta",
    "Jaggaiahpet",
    "Narasannapeta",
    "Repalle",
    "Tadepalligudem",
    "Piduguralla",
    "Tadepalligudem",
    "Dharmavaram",
    "Kavali",
    "Tiruvuru",
    "Mangalagiri",
    "Nandigama",
    "Vinukonda",
    "Ponnur",
    "Chilakaluripet",
    "Gudivada",
    "Peddapuram",
    "Samalkota",
    "Jaggaiahpet",
    "Nidadavole",
    "Tanuku",
    "Kandukur",
    "Rayachoti",
    "Palakollu",
    "Narasapuram",
    "Tuni",
    "Gudivada",
    "Mandapeta",
    "Srikalahasti",
    "Vinukonda",
    "Nandyal",
    "Venkatagiri",
    "Palasa Kasibugga",
    "Kadapa",
    "Punganur",
    "Venkatagiri",
    "Narasaraopet",
    "Adoni",
    "Tadepalligudem",
    "Bobbili",
    "Srikakulam",
    "Tadpatri",
    "Venkatagiri",
    "Samalkot",
    "Rayachoti",
    "Kadiri",
    "Giddalur",
    "Pulivendla",
    "Chirala",
    "Macherla",
    "Adoni",
    "Tadepalligudem",
    "Srikalahasti",
    "Bhongir",
    "Kandukur",
    "Rayachoti",
    "Palakollu",
    "Narasapuram",
    "Repalle",
    "Tadepalligudem",
    "Jaggaiahpet",
    "Pithapuram",
    "Kavali",
    "Markapur",
    "Yemmiganur",
    "Tadepalligudem",
    "Piduguralla",
    "Jaggayyapeta",
    "Venkatagiri",
    "Naidupet",
    "Punganur",
    "Bobbili",
    "Narasapuram",
    "Tuni",
    "Kavali",
    "Punganur",
    "Palwancha",
    "Narasannapeta",
    "Repalle",
    "Venkatagiri",
    "Rayachoti",
    "Srikalahasti",
    "Kavali",
    "Yemmiganur",
    "Tadepalligudem",
    "Palwancha",
    "Jammalamadugu",
    "Srikalahasti",
    "Naidupet",
    "Venkatagiri",
    "Tadepalligudem",
  ];
}

class ArunachalPradesh {
  static List<String> cities = [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Namsai",
    "Khonsa",
    "Bomdila",
    "Ziro",
    "Tawang",
    "Anini",
    "Changlang",
    "Roing",
    "Tezu",
    "Aalo",
    "Along",
    "Daporijo",
    "Yingkiong",
    "Mechuka",
    "Hawai",
    "Nampong",
    "Bhalukpong",
    "Seppa",
    "Tuting",
    "Vijaynagar",
    // Add more cities as needed
  ];
}

class Assam {
  static List<String> cities = [
  "Guwahati",
  "Silchar",
  "Dibrugarh",
  "Nagaon",
  "Jorhat",
  "Tinsukia",
  "Tezpur",
  "Bongaigaon",
  "Karimganj",
  "Sivasagar",
  "Barpeta",
  "Goalpara",
  "Dhubri",
  "Diphu",
  "North Lakhimpur",
  "Darrang",
  "Hailakandi",
  "Kokrajhar",
  "Nalbari",
  "Morigaon",
  "Sonitpur",
  "Bongaigaon City",
  "Dhemaji",
  "Dhubri",
  "Dibrugarh",
  "Diphu",
  "North Lakhimpur",
  "Silchar",
  "Tezpur",
  "Bilasipara",
  "Golaghat",
  "Guwahati",
  "Haflong",
  "Hailakandi",
  "Jorhat",
  "Karimganj",
  "Lakhimpur",
  "Lumding",
  "Mangaldoi",
  "Mariani",
  "Marigaon",
  "Nagaon",
  "Nalbari",
  "North Guwahati",
  "Rangia",
  "Sibsagar",
  "Silapathar",
  "Silchar",
  "Tezpur",
  "Tinsukia",
  "Umrangso",
  "Baihata Chariali",
  "Raha",
  "Namrup",
  "Mangaldai",
  "Rangapara",
  "Dhekiajuli",
  "Rupnagar",
  "Dhing",
  "Moranhat",
  "Gauripur",
  "Lumding",
  "Barpeta Road",
  "Sarupathar",
  "Sarthebari",
  "Sorbhog",
  "Thana",
  "Nazira",
  "Howli",
  "Kampur Town",
  "Golaghat",
  "Sibsagar",
  "Biswanath Chariali",
  "Bokajan",
  "Hojai",
  "Bihpuria",
  "Mahmora",
  "Rangapara",
  "Mangaldai",
  "Pathsala",
  "Laharighat",
  "Bokakhat",
  "Dhekiajuli",
  "Gossaigaon",
  "Kharupatia",
  "Silapathar",
  "Chapar",
  "Doboka",
  "Barpathar",
  "Haflong",
  "Tihu",
  "Bokakhat",
  "Barbari",
  "Barpathar",
  "Hajo",
  "Barpeta Road",
  "Biswanath Chariali",
  "Diphu",
  "Doboka",
  "Duliajan Oil Town",
  "Gohpur",
  "Kampur Town",
  "Lido Tikok",
  "Margherita",
  "Namrup",
  "Rangia",
  "Sarupathar",
  "Sibsagar",
  "Teok",
  "Titabor Town",
  "Umrangso",
  "Wahpeton",
  "Badarpur",
  "Bihpuria",
  "Bilasipara",
  "Bokajan",
  "Bokakhat",
  "Bongaigaon",
  "Chabua",
  "Chapar",
  "Dhekiajuli",
  "Dhemaji",
  "Dhubri",
  "Dibrugarh",
  "Digboi",
  "Dimapur",
  "Diphu",
  "Dispur",
  "Doboka",
  "Duliajan Oil Town",
  "Gauripur",
  "Goalpara",
  "Gohpur",
  "Golaghat",
  "Guwahati",
  "Haflong",
  "Hailakandi",
  "Hojai",
  "Jagiroad",
  "Jagiroad",
  "Jorhat",

];
}

class Bihar {
  static List<String> cities = [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Danapur",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri",
    "Siwan",
    "Motihari",
    "Nawada",
    "Bagaha",
    "Buxar",
    "Kishanganj",
    "Sitamarhi",
    "Jamalpur",
    "Jehanabad",
    "Aurangabad",
    "Lakhisarai",
    "Gopalganj",
    "Madhubani",
    "Samastipur",
    "Araria",
    "Masaurhi",
    "Nalanda",
    "Bettiah",
    "Sheikhpura",
    "Begusarai",
    "Kishanganj",
    "Jhanjharpur",
    "Araria",
    "Jamui",
    "Forbesganj",
    "Naugachhia",
    "Madhubani",
    "Supaul",
    "Mahnar Bazar",
    "Lalganj",
    "Raxaul Bazar",
    "Bhabua",
    "Narkatiaganj",
    "Asarganj",
    "Maharajganj",
    "Rajgir",
    "Dumraon",
    "Sherghati",
    "Sheikhpura",
    "Barh",
    "Bakhtiarpur",
    "Mokama",
    "Barauli",
    "Silao",
    "Koath",
    "Warisaliganj",
    "Bikramganj",
    "Marhaura",
    "Nokha",
    "Piro",
    "Buxar",
    "Lalganj",
    "Jagdispur",
    "Rafiganj",
    "Rajauli",
    "Warisnagar",
    "Naugachhia",
    "Daudnagar",
    "Amarpur",
    "Areraj",
    "Makhdumpur",
    "Maner",
    "Mahnar Bazar",
    "Silao",
    "Marhaura",
    "Lauriya",
    "Narkatiaganj",
    "Munger",
    "Ramnagar",
    "Manihari",
    "Barbigha",
    "Chandauli",
    "Sheohar",
    "Chhattapur",
    "Murliganj",
    "Purnia",
    "Lalganj",
    "Piro",
    "Obra",
    "Amber",
    "Mairwa",
    "Ramnagar",
    "Lalganj",
    "Masaurhi",
    "Nirmali",
    "Mahnar Bazar",
    "Sheikhpura",
    "Rafiganj",
    "Narkatiaganj",
    "Mahnar Bazar",
    "Rafiganj",
    "Masaurhi",
    "Sheikhpura",
    "Jagdishpur",
    "Nabinagar",
    "Murshidabad",
    "Maunath Bhanjan",
    "Saharsa",
    "Kesariya",
    "Mirganj",
    "Bodh Gaya",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Narkatiaganj",
    "Bhagalpur",
    "Banka",
    "Supaul",
    "Kumarganj",
    "Samastipur",
    "Forbesganj",
    "Bikramganj",
    "Munger",
    "Jamalpur",
    "Lakhisarai",
    "Hilsa",
    "Sheikhpura",
    "Munger",
    "Piro",
    "Marhaura",
    "Sheikhpura",
    "Narkatiaganj",
    "Sheikhpura",
    "Dumra",
    "Sheikhpura",
    "Narkatiaganj",
    "Dumra",
    "Masaurhi",
    "Nokha",
    "Rafiganj",
    "Buxar",
    "Kishanganj",
    "Chakia",
    "Piro",
    "Hilsa",
    "Narkatiaganj",
    "Raxaul Bazar",
    "Daudnagar",
    "Buxar",
    "Jagdishpur",
    "Masaurhi",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Rajauli",
    "Warisnagar",
    "Naugachhia",
    "Daudnagar",
    "Amarpur",
    "Areraj",
    "Makhdumpur",
    "Maner",
    "Mahnar Bazar",
    "Silao",
    "Marhaura",
    "Lauriya",
    "Narkatiaganj",
    "Munger",
    "Ramnagar",
    "Manihari",
    "Barbigha",
    "Chandauli",
    "Sheohar",
    "Chhattapur",
    "Murliganj",
    "Purnia",
    "Lalganj",
    "Piro",
    "Obra",
    "Amber",
    "Mairwa",
    "Ramnagar",
    "Lalganj",
    "Masaurhi",
    "Nirmali",
    "Mahnar Bazar",
    "Sheikhpura",
    "Rafiganj",
    "Narkatiaganj",
    "Mahnar Bazar",
    "Rafiganj",
    "Masaurhi",
    "Sheikhpura",
    "Jagdishpur",
    "Nabinagar",
    "Murshidabad",
    "Maunath Bhanjan",
    "Saharsa",
    "Kesariya",
    "Mirganj",
    "Bodh Gaya",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Narkatiaganj",
    "Bhagalpur",
    "Banka",
    "Supaul",
    "Kumarganj",
    "Samastipur",
    "Forbesganj",
    "Bikramganj",
    "Munger",
    "Jamalpur",
    "Lakhisarai",
    "Hilsa",
    "Sheikhpura",
    "Munger",
    "Piro",
    "Marhaura",
    "Sheikhpura",
    "Narkatiaganj",
    "Sheikhpura",
    "Dumra",
    "Sheikhpura",
    "Narkatiaganj",
    "Dumra",
    "Masaurhi",
    "Nokha",
    "Rafiganj",
    "Buxar",
    "Kishanganj",
    "Chakia",
    "Piro",
    "Hilsa",
    "Narkatiaganj",
    "Raxaul Bazar",
    "Daudnagar",
    "Buxar",
    "Jagdishpur",
    "Masaurhi",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Rajauli",
    "Warisnagar",
    "Naugachhia",
    "Daudnagar",
    "Amarpur",
    "Areraj",
    "Makhdumpur",
    "Maner",
    "Mahnar Bazar",
    "Silao",
    "Marhaura",
    "Lauriya",
    "Narkatiaganj",
    "Munger",
    "Ramnagar",
    "Manihari",
    "Barbigha",
    "Chandauli",
    "Sheohar",
    "Chhattapur",
    "Murliganj",
    "Purnia",
    "Lalganj",
    "Piro",
    "Obra",
    "Amber",
    "Mairwa",
    "Ramnagar",
    "Lalganj",
    "Masaurhi",
    "Nirmali",
    "Mahnar Bazar",
    "Sheikhpura",
    "Rafiganj",
    "Narkatiaganj",
    "Mahnar Bazar",
    "Rafiganj",
    "Masaurhi",
    "Sheikhpura",
    "Jagdishpur",
    "Nabinagar",
    "Murshidabad",
    "Maunath Bhanjan",
    "Saharsa",
    "Kesariya",
    "Mirganj",
    "Bodh Gaya",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Narkatiaganj",
    "Bhagalpur",
    "Banka",
    "Supaul",
    "Kumarganj",
    "Samastipur",
    "Forbesganj",
    "Bikramganj",
    "Munger",
    "Jamalpur",
    "Lakhisarai",
    "Hilsa",
    "Sheikhpura",
    "Munger",
    "Piro",
    "Marhaura",
    "Sheikhpura",
    "Narkatiaganj",
    "Sheikhpura",
    "Dumra",
    "Sheikhpura",
    "Narkatiaganj",
    "Dumra",
    "Masaurhi",
    "Nokha",
    "Rafiganj",
    "Buxar",
    "Kishanganj",
    "Chakia",
    "Piro",
    "Hilsa",
    "Narkatiaganj",
    "Raxaul Bazar",
    "Daudnagar",
    "Buxar",
    "Jagdishpur",
    "Masaurhi",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Rajauli",
    "Warisnagar",
    "Naugachhia",
    "Daudnagar",
    "Amarpur",
    "Areraj",
    "Makhdumpur",
    "Maner",
    "Mahnar Bazar",
    "Silao",
    "Marhaura",
    "Lauriya",
    "Narkatiaganj",
    "Munger",
    "Ramnagar",
    "Manihari",
    "Barbigha",
    "Chandauli",
    "Sheohar",
    "Chhattapur",
    "Murliganj",
    "Purnia",
    "Lalganj",
    "Piro",
    "Obra",
    "Amber",
    "Mairwa",
    "Ramnagar",
    "Lalganj",
    "Masaurhi",
    "Nirmali",
    "Mahnar Bazar",
    "Sheikhpura",
    "Rafiganj",
    "Narkatiaganj",
    "Mahnar Bazar",
    "Rafiganj",
    "Masaurhi",
    "Sheikhpura",
    "Jagdishpur",
    "Nabinagar",
    "Murshidabad",
    "Maunath Bhanjan",
    "Saharsa",
    "Kesariya",
    "Mirganj",
    "Bodh Gaya",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Narkatiaganj",
    "Bhagalpur",
    "Banka",
    "Supaul",
    "Kumarganj",
    "Samastipur",
    "Forbesganj",
    "Bikramganj",
    "Munger",
    "Jamalpur",
    "Lakhisarai",
    "Hilsa",
    "Sheikhpura",
    "Munger",
    "Piro",
    "Marhaura",
    "Sheikhpura",
    "Narkatiaganj",
    "Sheikhpura",
    "Dumra",
    "Sheikhpura",
    "Narkatiaganj",
    "Dumra",
    "Masaurhi",
    "Nokha",
    "Rafiganj",
    "Buxar",
    "Kishanganj",
    "Chakia",
    "Piro",
    "Hilsa",
    "Narkatiaganj",
    "Raxaul Bazar",
    "Daudnagar",
    "Buxar",
    "Jagdishpur",
    "Masaurhi",
    "Nokha",
    "Piro",
    "Rafiganj",
    "Rajauli",
    "Warisnagar",
    "Naugachhia",
    "Daudnagar",
    "Amarpur",
    "Areraj",
    "Makhdumpur",
    "Maner",
    "Mahnar Bazar",
    "Silao",
    "Marhaura",
    "Lauriya",
    "Narkatiaganj",
    "Munger",
    "Ramnagar",
    "Manihari",
    "Barbigha",
    "Chandauli",
    "Sheohar",
    "Chhattapur",
    "Murliganj",
    "Purnia",
    "Lalganj",
    "Piro",
    "Obra",

  ];
}
class Chandigarh {
  static List<String> cities = [
    "Chandigarh",
    // No other major cities in the union territory
  ];
}

class Chhattisgarh {
  static List<String> cities = [
    "Raipur",
    "Bhilai",
    "Durg",
    "Bilaspur",
    "Korba",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Chirmiri",
    "Dhamtari",
    "Mahasamund",
    "Rajnandgaon",
    "Jagdalpur",
    "Korba",
    "Rajnandgaon",
    "Bilaspur",
    "Bhatapara",
    "Dhamtari",
    "Dalli-Rajhara",
    "Mahasamund",
    "Raigarh",
    "Rajpur",
    "Jagdalpur",
    "Naila Janjgir",
    "Tilda Newra",
    "Raigarh",
    "Sakti",
    "Mahasamund",
    "Simga",
    "Naila Janjgir",
    "Tilda Newra",
    "Sakti",
    "Bhatapara",
    "Tilda Newra",
    "Simga",
    "Baloda Bazar",
    "Chirmiri",
    "Manendragarh",
    "Naila Janjgir",
    "Mungeli",
    "Jashpurnagar",
    "Bade Bacheli",
    "Akaltara",
    "Gandai",
    "Khairagarh",
    "Jashpurnagar",
    "Bade Bacheli",
    "Akaltara",
    "Gandai",
    "Khairagarh",
    "Kanker",
    "Simga",
    "Bhatapara",
    "Bhatgaon",
    "Kawardha",
    "Mungeli",
    "Simga",
    "Bhatapara",
    "Bhatgaon",
    "Kawardha",
    "Kanker",
    "Bade Bacheli",
    "Akaltara",
    "Jashpurnagar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
    "Baloda",
    "Baloda Bazar",
    "Gandai",
    "Khairagarh",
    "Baloda Bazar",
  ];
}

class DadraAndNagarHaveli {
  static List<String> cities = [
    "Silvassa",
    "Amli",
    "Naroli",
    "Rakholi",
    "Vapi",
    "Khadoli",
    "Dadra",
    "Saily",
    "Udva",
    "Dahikhed",
    "Galonda",
    "Luari",
    "Athal",
    "Kanadi",
    "Matiyari",
    "Nagracem",
    "Patripul",
    "Rudana",
    "Samarvani",
    "Sili",
    "Sinchavali",
    "Udva",
    "Velugam",
  ];
}

class DamanAndDiu {
  static List<String> cities = [
    "Daman",
    "Diu",
    "Moti Daman",
    "Nani Daman",
    "Dabhel",
    "Kachigam",
    "Marwad",
    "Zari",
    "Athola",
    "Dholar",
    "Dadhel",
    "Devka",
    "Dunetha",
    "Fudam",
    "Galwada",
    "Kadaiya",
    "Kunta",
    "Nagwa",
    "Rajiv Nagar",
    "Ringanwada",
    "Simbor",
    "Varkund",
    "Vanakbara",
  ];
}

class Delhi {
  static List<String> cities = [
    "New Delhi",
    "Delhi",
    "Noida",
    "Gurgaon",
    "Faridabad",
    "Ghaziabad",
    "Bahadurgarh",
    "South Delhi",
    "North Delhi",
    "East Delhi",
    "West Delhi",
    "Central Delhi",
    "Saket",
    "Connaught Place",
    "Dwarka",
    "Pitampura",
    "Vasant Kunj",
    "Rohini",
    "Greater Kailash",
    "Laxmi Nagar",
    "Janakpuri",
    "Karol Bagh",
    "Chandni Chowk",
    "Nehru Place",
    "Paharganj",
    "Kalkaji",
    "Chanakyapuri",
    "Lajpat Nagar",
    "Narela",
    "Patel Nagar",
    "Mayur Vihar",
    "Sarita Vihar",
    "Khanpur",
    "Civil Lines",
    "Defence Colony",
    "Hauz Khas",
    "Rajouri Garden",
    "Sadar Bazaar",
    "Saket",
    "Sarita Vihar",
    "Shahdara",
    "Sultanpur Majra",
    "Vasant Vihar",
    "Kanjhawala",
    "Seelampur",
    "Mehrauli",
    "Karawal Nagar",
    "Sonia Vihar",
    "Delhi Cantonment",
    "Gharoli",
    "Rani Bagh",
    "Nangloi Jat",
    "Burari",
    "Bhalswa Jahangir Pur",
    "Patparganj",
    "Shalimar Bagh",
    "Sonia Vihar",
    "Seelampur",
    "Rani Khera",
    "Mandoli",
    "Dallo Pura",
    "Bakhtawarpur",
    "Sarup Nagar",
    "Qutabgarh",
    "Bawana",
    "Mubarikpur Dabas",
    "Neb Sarai",
    "Mandoli",
    "Jharoda Majraa",
    "Gokalpur",
    "Alipur",
    "Baprola",
    "Sant Nagar",
    "Shahdara",
    "Kirari Suleman Nagar",
    "Pooth Khurd",
    "Sultanpur Majra",
    "Khera Kalan",
    "Bakhtawarpur",
    "Bhalswa Jahangir Pur",
    "Karawal Nagar",
    "Kanjhawala",
    "Dallo Pura",
    "Mubarak Pur Dabas",
    "Nangli Sakrawati",
    "Mukhmelpur",
    "Budh Vihar",
    "Ghuman Hera",
    "Rohini sub city",
    "Jaffrabad",
    "Sunder Nagri",
    "Burari",
    "Timarpur",
    "Narela",
    "Alipur",
    "Burari",
    "Timarpur",
    "Karawal Nagar",
    "Bhalswa Jahangir Pur",
    "Sultanpur Majra",
    "Najafgarh",
    "Baprola",
    "Dichaon Kalan",
    "Najafgarh",
    "Narela",
    "Bawana",
    "Narela",
    "Alipur",
    "Rohini sub city",
    "Rohini sub city",
    "Ghoga",
    "Budh Vihar",
    "Pooth Kalan",
    "Kirari Suleman Nagar",
    "Najafgarh",
    "Dichaon Kalan",
    "Narela",
    "Bawana",

  ];
}

class Goa {
  static List<String> cities = [
    "Panaji",
    "Vasco da Gama",
    "Margao",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Cuncolim",
    "Curchorem",
    "Mapusa",
    "Panaji",
    "Pernem",
    "Quepem",
    "Sancoale",
    "Valpoi",
    "Verem",
    "Verna",
  ];
}

class Gujarat {
  static List<String> cities = [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Gandhidham",
    "Nadiad",
    "Morbi",
    "Anand",
    "Surendranagar",
    "Bharuch",
    "Vapi",
    "Navsari",
    "Mehsana",
    "Gujarat",
    "Bhuj",
    "Ankleshwar",
    "Godhra",
    "Patan",
    "Dahod",
    "Valsad",
    "Palanpur",
    "Porbandar",
    "Vapi",
    "Botad",
    "Kapadvanj",
    "Kalol",
    "Una",
    "Amreli",
    "Jetpur",
    "Vapi",
    "Viramgam",
    "Deesa",
    "Visnagar",
    "Kadi",
    "Dhoraji",
    "Upleta",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Bantwa",
    "Bhabhar",
    "Rapar",
    "Salaya",
    "Sanand",
    "Rajula",
    "Sidhpur",
    "Mansa",
    "Umreth",
    "Mangrol",
    "Limbdi",
    "Mandvi",
    "Savarkundla",
    "Lathi",
    "Kathor",
    "Umreth",
    "Modasa",
    "Vallabh Vidhyanagar",
    "Wadhwan",
    "Mahuva",
    "Rajpipla",
    "Tharad",
    "Mahesana",
    "Keshod",
    "Siddhpur",
    "Visavadar",
    "Vijapur",
    "Pardi",
    "Halvad",
    "Manavadar",
    "Lunawada",
    "Umreth",
    "Modasa",
    "Vallabh Vidhyanagar",
    "Wadhwan",
    "Mahuva",
    "Rajpipla",
    "Tharad",
    "Mahesana",
    "Keshod",
    "Siddhpur",
    "Visavadar",
    "Vijapur",
    "Pardi",
    "Halvad",
    "Manavadar",
    "Lunawada",
    "Wankaner",
    "Padra",
    "Lakhtar",
    "Vijalpor",
    "Vadnagar",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Gandhidham",
    "Nadiad",
    "Morbi",
    "Anand",
    "Surendranagar",
    "Bharuch",
    "Vapi",
    "Navsari",
    "Mehsana",
    "Gujarat",
    "Bhuj",
    "Ankleshwar",
    "Godhra",
    "Patan",
    "Dahod",
    "Valsad",
    "Palanpur",
    "Porbandar",
    "Vapi",
    "Botad",
    "Kapadvanj",
    "Kalol",
    "Una",
    "Amreli",
    "Jetpur",
    "Vapi",
    "Viramgam",
    "Deesa",
    "Visnagar",
    "Kadi",
    "Dhoraji",
    "Upleta",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Nadiad",
    "Visavadar",
    "Siddhpur",
    "Vijapur",
    "Bantwa",
    "Bhabhar",
    "Rapar",
    "Salaya",
    "Sanand",
    "Rajula",
    "Sidhpur",
    "Mansa",
    "Umreth",
    "Mangrol",
    "Limbdi",
    "Mandvi",
    "Savarkundla",
    "Lathi",
    "Kathor",
    "Umreth",
    "Modasa",
    "Vallabh Vidhyanagar",
    "Wadhwan",
    "Mahuva",
    "Rajpipla",
    "Tharad",
    "Mahesana",
    "Keshod",
    "Siddhpur",
    "Visavadar",
    "Vijapur",
    "Pardi"
  ];
}

class Haryana {
  static List<String> cities = [
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Hansi",
    "Narnaul",
    "Fatehabad",
    "Gohana",
    "Tohana",
    "Narwana",
    "Ladwa",
    "Sasaram",
    "Shahabad",
    "Samalkha",
    "Pinjore",
    "Safidon",
    "Ratia",
    "Rania",
    "Narayangarh",
    "Jhajjar",
    "Uchana",
    "Kosli",
    "Thanesar",
    "Dharuhera",
    "Barwala",
    "Charkhi Dadri",
    "Pehowa",
    "Radaur",
    "Taraori",
    "Mahendragarh",
    "Sukhrali",
    "Babiyal",
    "Gharaunda",
    "Farrukhnagar",
    "Jakhal Mandi",
    "Narnaund",
    "Punahana",
    "Pundri",
    "Shahabad",
    "Sidhrawali",
    "Tauru",
    "Ferozepur Jhirka",
    "Guhla",
    "Pataudi",
    "Tosham",
    "Haileymandi",
    "Safidon",
    "Shahabad Markanda",
    "Uklana Mandi",
    "Adampur",
    "Bahadurganj",
    "Barara",
    "Beri",
    "Chhachhrauli",
    "Chhatar",
    "Dhanaula",
    "Ganaur",
    "Gharaunda",
    "Gohana",
    "Guru Har Sahai",
    "Indri",
    "Ismailabad",
    "Jagadhri",
    "Jagadhri",
    "Jagadhri",
    "Jhajjar",
    "Jind",
    "Julana",
    "Kalanaur",
    "Kalayat",
    "Kalka",
    "Kanina",
    "Kharkhoda",
    "Kiloi",
    "Ladwa",
    "Madlauda",
    "Mahendragarh",
    "Mandi Dabwali",
    "Naraingarh",
    "Narnaund",
    "Nilokheri",
    "Nuh",
    "Pehowa",
    "Pundri",
    "Punhana",
    "Rania",
    "Ratia",
    "Rewari",
    "Safidon",
    "Samalkha",
    "Shahabad",
    "Shahbad",
    "Shahbad",
    "Shahpur",
    "Sirsa",
    "Sohna",
    "Taraori",
    "Thanesar",
    "Tosham",
    "Uchana",
    "Uklana Mandi",
    "Un",
    "Yamunanagar",
    "Chandigarh",
    "Dharuhera",
    "Farrukhnagar",
    "Hansi",
    "Jakhal Mandi",
    "Kaithal",
    "Karnal",
    "Kosli",
    "Pataudi",
    "Pinjore",
    "Radaur",
    "Raipur Rani",
    "Ratia",

  ];
}

class HimachalPradesh {
  static List<String> cities = [
    "Shimla",
    "Mandi",
    "Solan",
    "Dharamshala",
    "Palampur",
    "Una",
    "Nahan",
    "Sirmaur",
    "Kangra",
    "Bilaspur",
    "Kullu",
    "Chamba",
    "Hamirpur",
    "Nurpur",
    "Paonta Sahib",
    "Jawalamukhi",
    "Nagrota",
    "Pragpur",
    "Tira Sujanpur",
    "Dagshai",
    "Dalhousie",
    "Jawalamukhi",
    "Jutogh",
    "Kangra",
    "Kasauli",
    "Kasumpti",
    "Keylong",
    "Kufri",
    "Manali",
    "Mandi",
    "Mant Khas",
    "Mehatpur Basdehra",
    "Nadaun",
    "Nagrota Bagwan",
    "Nahan",
    "Naina Devi",
    "Palampur",
    "Pandoh",
    "Paonta Sahib",
    "Parwanoo",
    "Chamba",
    "Dharamshala",
    "Nalagarh",
    "Rampur",
    "Reckong Peo",
    "Rohru",
    "Santokhgarh",
    "Seoni",
    "Shahpur",
    "Shimla",
    "Solan",
    "Sundarnagar",
    "Talai",
    "Theog",
    "Tira Sujanpur",
    "Una",
    "Yol",
    "Bhota",
    "Daulatpur",
    "Gagret",
    "Ghamarwin",
    "Jogindernagar",
    "Kangra",
    "Kotkhai",
    "Kullu",
    "Manali",
    "Mandi",
    "Mehatpur Basdehra",
    "Nurpur",
    "Palampur",
    "Rampur",
    "Shimla",
    "Solan",
    "Sundarnagar",
    "Tira Sujanpur",
    "Una",
    "Yol",
    "Bhota",
    "Daulatpur",
    "Gagret",
    "Ghamarwin",
    "Jogindernagar",
    "Kangra",
    "Kotkhai",
    "Kullu",
    "Manali",
    "Mandi",
    "Mehatpur Basdehra",
    "Nurpur",
    "Palampur",
    "Rampur",
    "Shimla",
    "Solan",
    "Sundarnagar",
    "Tira Sujanpur",
    "Una",
    "Yol",
    "Bhota",
    "Daulatpur",
    "Gagret",
    "Ghamarwin",
    "Jogindernagar",
    "Kangra",
    "Kotkhai",
    "Kullu",
    "Manali",
    "Mandi",
    "Mehatpur Basdehra",
    "Nurpur",
    "Palampur",
    "Rampur",
    "Shimla",
    "Solan",
    "Sundarnagar",
    "Tira Sujanpur",
    "Una",
    "Yol",
    "Bhota",
    "Daulatpur",
    "Gagret",
    "Ghamarwin",
    "Jogindernagar",
    "Kangra",
    "Kotkhai",
    "Kullu",
    "Manali",
    "Mandi",
    "Mehatpur Basdehra",
    "Nurpur",
    "Palampur",
    "Rampur",
    "Shimla",
    "Solan",
    "Sundarnagar",
    "Tira Sujanpur",
    "Una",
    "Yol",
  ];
}

class Jharkhand {
  static List<String> cities = [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Chirkunda",
    "Jhumri Tilaiya",
    "Saunda",
    "Sahibganj",
    "Dumka",
    "Pakaur",
    "Chaibasa",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Giridih",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Giridih",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Hazaribagh",
    "Jhumri Tilaiya",
    "Ramgarh",
    "Medininagar",
    "Chirkunda",
    "Jhumri Tilaiya",
    "Saunda",
    "Sahibganj",
    "Dumka",
    "Pakaur",
    "Chaibasa",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Giridih",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Giridih",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
    "Giridih",
    "Gumia",
    "Bokaro",
    "Chatra",
    "Gomoh",
    "Gobindpur",
    "Godda",
    "Daltonganj",
    "Jamtara",
    "Garhwa",
    "Nirsa",
    "Simdega",
  ];
}

class Karnataka {
  static List<String> cities = [
    "Bangalore",
    "Mysore",
    "Hubli-Dharwad",
    "Mangalore",
    "Belgaum",
    "Gulbarga",
    "Davanagere",
    "Bellary",
    "Bijapur",
    "Shimoga",
    "Tumkur",
    "Raichur",
    "Bidar",
    "Hospet",
    "Hassan",
    "Gadag-Betageri",
    "Udupi",
    "Robertson Pet",
    "Mandya",
    "Chitradurga",
    "Chikmagalur",
    "Gangawati",
    "Bagalkot",
    "Kolar",
    "Dharwad",
    "Mudhol",
    "Bhadravati",
    "Shahabad",
    "Rabkavi Banhatti",
    "Haveri",
    "Channarayapatna",
    "Tiptur",
    "Karkala",
    "Ranibennur",
    "Ramanagaram",
    "Gokak",
    "Nipani",
    "Adyar",
    "Bhatkal",
    "Chintamani",
    "Sakleshpur",
    "Sindhnur",
    "Sira",
    "Surapura",
    "Talikota",
    "Arkalgud",
    "Arvi",
    "Adityapatna",
    "Aland",
    "Anekal",
    "Athni",
    "Aurad",
    "Bagepalli",
    "Bailhongal",
    "Bangarapet",
    "Bantwal",
    "Basavakalyan",
    "Basavana Bagevadi",
    "Bhalki",
    "Bijapur",
    "Channagiri",
    "Chik Ballapur",
    "Chiknayakanhalli",
    "Chincholi",
    "Chitapur",
    "Chikodi",
    "Dasarahalli",
    "Gubbi",
    "Haliyal",
    "Hangal",
    "Harki",
    "Hirekerur",
    "Hiriyur",
    "Holalkere",
    "Hunsur",
    "Hunswar",
    "Indi",
    "Jagalur",
    "Jamkhandi",
    "Jevargi",
    "Kadur",
    "Kalghatgi",
    "Kanakapura",
    "Kapu",
    "Karwar",
    "Khanapur",
    "Kodagu",
    "Kodigenahalli",
    "Kodiyal",
    "Kolar",
    "Kollegal",
    "Konanur",
    "Koppal",
    "Krishnarajpet",
    "Kudligi",
    "Lakshmeshwar",
    "Lingsugur",
    "Maddur",
    "Madhugiri",
    "Malavalli",
    "Malur",
    "Manvi",
    "Mudalgi",
    "Muddebihal",
    "Mudhol",
    "Mundargi",
    "Mysore",
    "Nanjangud",
    "Nargund",
    "Navalgund",
    "Nelamangala",
    "Pavagada",
    "Puttur",
    "Rabkavi Banhatti",
    "Raibag",
    "Ramanagaram",
    "Ramdurg",
    "Ron",
    "Sagar",
    "Sakaleshapura",
    "Sedam",
    "Shahabad",
    "Shahpur",
    "Shaktinagar",
    "Shiggaon",
    "Shikaripur",
    "Shivamogga",
    "Shrirangapattana",
    "Sidlaghatta",
    "Sindagi",
    "Sindhnur",
    "Sira",
    "Sirsi",
    "Siruguppa",
    "Sorab",
    "Srinivaspur",
    "Tarikere",
    "Tekkalakote",
    "Terdal",
    "Tiptur",
    "Tumkur",
    "Udupi",
    "Vijayapura",
    "Wadi",
    "Yadgir",
    "Yelahanka",
    "Yelbarga",
    "Yellapur",
  ];
}

class Kerala {
  static List<String> cities = [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kollam",
    "Thrissur",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Thiruvalla",
    "Kasaragod",
    "Malappuram",
    "Neyyattinkara",
    "Kayamkulam",
    "Kanhangad",
    "Nileshwar",
    "Kochi",
    "Thiruvananthapuram",
    "Kollam",
    "Thrissur",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Thiruvalla",
    "Kasaragod",
    "Malappuram",
    "Neyyattinkara",
    "Kayamkulam",
    "Kanhangad",
    "Nileshwar",
    "Kochi",
    "Thiruvananthapuram",
    "Kollam",
    "Thrissur",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Thiruvalla",
    "Kasaragod",
    "Malappuram",
    "Neyyattinkara",
    "Kayamkulam",
    "Kanhangad",
    "Nileshwar",
    "Kochi",
    "Thiruvananthapuram",
    "Kollam",
    "Thrissur",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Thiruvalla",
    "Kasaragod",
    "Malappuram",
    "Neyyattinkara",
    "Kayamkulam",
    "Kanhangad",
    "Nileshwar",
  ];
}

class MadhyaPradesh {
  static List<String> cities = [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara (Katni)",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
    "Chhatarpur",
    "Damoh",
    "Mandsaur",
    "Khargone",
    "Neemuch",
    "Pithampur",
    "Hoshangabad",
    "Itarsi",
    "Sehore",
    "Betul",
    "Seoni",
    "Datia",
    "Nagda",
    "Harda",
    "Mhow Cantonment",
    "Dabra",
    "Maharajpur",
    "Sendhwa",
    "Mandla",
    "Mhowgaon",
    "Sironj",
    "Bamor Kalan",
    "Gwalior",
    "Nagda",
    "Khachrod",
    "Shujalpur",
    "Ashok Nagar",
    "Mahidpur",
    "Pipariya",
    "Lahar",
    "Kotma",
    "Maheshwar",
    "Manawar",
    "Panna",
    "Pipariya",
    "Porsa",
    "Prithvipur",
    "Raghogarh",
    "Rahatgarh",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rau",
    "Rehli",
  ];
}



class Maharashtra {
  static List<String> cities = [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Malegaon",
    "Kolhapur",
    "Nanded",
    "Sangli",
    "Jalgaon",
    "Akola",
    "Latur",
    "Ahmednagar",
    "Dhule",
    "Ichalkaranji",
    "Chandrapur",
    "Parbhani",
    "Jalna",
    "Bhusawal",
    "Navi Mumbai",
    "Panvel",
    "Satara",
    "Beed",
    "Yavatmal",
    "Kamptee",
    "Gondia",
    "Barshi",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat",
    "Chandrapur",
    "Parbhani",
    "Jalna",
    "Bhusawal",
    "Navi Mumbai",
    "Panvel",
    "Satara",
    "Beed",
    "Yavatmal",
    "Kamptee",
    "Gondia",
    "Barshi",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat",
    "Chandrapur",
    "Parbhani",
    "Jalna",
    "Bhusawal",
    "Navi Mumbai",
    "Panvel",
    "Satara",
    "Beed",
    "Yavatmal",
    "Kamptee",
    "Gondia",
    "Barshi",
    "Achalpur",
    "Osmanabad",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat",
  ];
}

class Manipur {
  static List<String> cities = [
    "Imphal",
    "Thoubal",
    "Kakching",
    "Lilong",
    "Mayang Imphal",
    "Nambol",
    "Wangoi",
    "Wangjing",
    "Yairipok",
    "Bishnupur",
    "Churachandpur",
    "Kumbi",
    "Kwakta",
    "Moirang",
    "Moreh",
    "Ningthoukhong",
    "Sugnu",
    "Kakching",
    "Lilong",
    "Mayang Imphal",
    "Nambol",
    "Wangoi",
    "Wangjing",
    "Yairipok",
    "Bishnupur",
    "Churachandpur",
    "Kumbi",
    "Kwakta",
    "Moirang",
    "Moreh",
    "Ningthoukhong",
    "Sugnu",
    "Kakching",
    "Lilong",
    "Mayang Imphal",
    "Nambol",
    "Wangoi",
    "Wangjing",
    "Yairipok",
    "Bishnupur",
    "Churachandpur",
    "Kumbi",
    "Kwakta",
    "Moirang",
    "Moreh",
    "Ningthoukhong",
    "Sugnu",
  ];
}

class Meghalaya {
  static List<String> cities = [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongstoin",
    "Williamnagar",
    "Baghmara",
    "Resubelpara",
    "Khliehriat",
    "Mairang",
    "Nongpoh",
    "Dawki",
    "Cherrapunji",
    "Nongpoh",
    "Dawki",
    "Cherrapunji",
    "Nongpoh",
    "Dawki",
    "Cherrapunji",
    "Nongpoh",
    "Dawki",
    "Cherrapunji",
    "Nongpoh",
    "Dawki",
    "Cherrapunji",
  ];
}

class Mizoram {
  static List<String> cities = [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Lawngtlai",
    "Saitual",
    "Khawzawl",
    "Hnahthial",
    "Tlabung",
    "Biate",
    "Buarpui",
    "N. Vanlaiphai",
    "Zawlnuam",
    "Ngopa",
    "Tlangnuam",
    "N. Khawbung",
    "Ratu",
    "Zokhawthar",
    "Zemabawk",
    "Rajiv Nagar",
    "Zamualphai",
    "Darlawn",
    "Saiha",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Lawngtlai",
    "Saitual",
    "Khawzawl",
    "Hnahthial",
    "Tlabung",
    "Biate",
    "Buarpui",
    "N. Vanlaiphai",
    "Zawlnuam",
    "Ngopa",
    "Tlangnuam",
    "N. Khawbung",
    "Ratu",
    "Zokhawthar",
    "Zemabawk",
    "Rajiv Nagar",
    "Zamualphai",
    "Darlawn",
  ];
}

class Nagaland {
  static List<String> cities = [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Kiphire",
    "Longleng",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
    "Chumukedima",
  ];
}

class Odisha {
  static List<String> cities = [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Bhawanipatna",
    "Bargarh",
    "Jeypore",
    "Jharsuguda",
    "Rayagada",
    "Bolangir",
    "Nabarangpur",
    "Kendrapara",
    "Paradip",
    "Jagatsinghpur",
    "Sunabeda",
    "Brahmapur",
    "Dhenkanal",
    "Bhadrak",
    "Baripada",
    "Bhawanipatna",
    "Bargarh",
    "Jeypore",
    "Jharsuguda",
    "Rayagada",
    "Bolangir",
    "Nabarangpur",
    "Kendrapara",
    "Paradip",
    "Jagatsinghpur",
    "Sunabeda",
    "Brahmapur",
    "Dhenkanal",
    "Bhadrak",
    "Baripada",
    "Bhawanipatna",
    "Bargarh",
    "Jeypore",
    "Jharsuguda",
    "Rayagada",
    "Bolangir",
    "Nabarangpur",
    "Kendrapara",
    "Paradip",
    "Jagatsinghpur",
    "Sunabeda",
    "Brahmapur",
    "Dhenkanal",
  ];
}

class Punjab {
  static List<String> cities = [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Mohali",
    "Batala",
    "Pathankot",
    "Moga",
    "Firozpur",
    "Kapurthala",
    "Rajpura",
    "Khanna",
    "Muktsar",
    "Barnala",
    "Gurdaspur",
    "Sangrur",
    "Faridkot",
    "Fatehgarh Sahib",
    "Abohar",
    "Malerkotla",
    "Nabha",
    "Patti",
    "Samana",
    "Sardulgarh",
    "Sujanpur",
    "Tarn Taran",
    "Zira",
    "Budhlada",
    "Jagraon",
    "Kalanaur",
    "Lalru",
    "Mansa",
    "Moga",
    "Moonak",
    "Morinda",
    "Mukerian",
    "Mullanpur Dakha",
    "Nakodar",
    "Nawanshahr",
    "Nurmahal",
    "Pathankot",
    "Patti",
    "Payal",
    "Phagwara",
    "Phillaur",
    "Qadian",
    "Raikot",
    "Rampura Phul",
    "Rayya",
    "Rupnagar",
    "Samana",
    "Samrala",
    "Sanaur",
    "Sangrur",
    "Shahkot",
    "Sham Chaurasi",
    "Shekhpura",
    "Sirhind Fatehgarh Sahib",
    "Sultanpur Lodhi",
    "Sunam",
    "Talwandi Bhai",
    "Talwara",
    "Tappa Mandi",
    "Tarn Taran",
    "Urmar Tanda",
    "Zira",
  ];
}

class Rajasthan {
  static List<String> cities = [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Sri Ganganagar",
    "Barmer",
    "Tonk",
    "Kishangarh",
    "Beawar",
    "Hanumangarh",
    "Dholpur",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
    "Churu",
    "Sawai Madhopur",
    "Nagaur",
    "Chittorgarh",
  ];
}

class Sikkim {
  static List<String> cities = [
    "Gangtok",
    "Namchi",
    "Mangan",
    "Jorethang",
    "Rangpo",
    "Singtam",
    "Naya Bazar",
    "Melli",
    "Gyalshing",
    "Soreng",
    "Ravangla",
    "Rhenock",
    "Mangan",
    "Jorethang",
    "Rangpo",
    "Singtam",
    "Naya Bazar",
    "Melli",
    "Gyalshing",
    "Soreng",
    "Ravangla",
    "Rhenock",
    "Mangan",
    "Jorethang",
    "Rangpo",
    "Singtam",
    "Naya Bazar",
    "Melli",
    "Gyalshing",
    "Soreng",
    "Ravangla",
    "Rhenock",
  ];
}

class TamilNadu {
  static List<String> cities = [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Ooty",
    "Pollachi",
    "Rajapalayam",
    "Nagercoil",
    "Kanchipuram",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pudukkottai",
    "Hosur",
    "Neyveli",
    "Nagapattinam",
    "Vaniyambadi",
    "Ambur",
    "Nagercoil",
    "Kanchipuram",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pudukkottai",
    "Hosur",
    "Neyveli",
    "Nagapattinam",
    "Vaniyambadi",
    "Ambur",
    "Nagercoil",
    "Kanchipuram",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pudukkottai",
    "Hosur",
    "Neyveli",
    "Nagapattinam",
    "Vaniyambadi",
    "Ambur",
    "Nagercoil",
    "Kanchipuram",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pudukkottai",
    "Hosur",
    "Neyveli",
    "Nagapattinam",
    "Vaniyambadi",
    "Ambur",
  ];
}

class Telangana {
  static List<String> cities = [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Jagtial",
    "Nirmal",
    "Koratla",
    "Mandamarri",
    "Kagaznagar",
    "Wanaparthy",
    "Kothagudem",
    "Palwancha",
    "Yellandu",
    "Manuguru",
    "Bellampalle",
    "Kyathampalle",
    "Bhainsa",
    "Vikarabad",
    "Jangaon",
    "Bhongir",
    "Siddipet",
    "Sangareddy",
    "Medak",
    "Kothur",
    "Shadnagar",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
    "Bhadrachalam",
  ];
}

class Tripura {
  static List<String> cities = [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailasahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Amarpur",
    "Sonamura",
    "Jogendranagar",
    "Teliamura",
    "Bishalgarh",
    "Kanchanpur",
    "Bishramganj",
    "Melaghar",
    "Kalayanpur",
    "Kumarghat",
    "Gakulnagar",
    "Ranirbazar",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Amarpur",
    "Sonamura",
    "Jogendranagar",
    "Teliamura",
    "Bishalgarh",
    "Kanchanpur",
    "Bishramganj",
    "Melaghar",
    "Kalayanpur",
    "Kumarghat",
    "Gakulnagar",
    "Ranirbazar",
  ];
}

class UttarPradesh {
  static List<String> cities = [
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj",
    "Ghaziabad",
    "Noida",
    "Moradabad",
    "Aligarh",
    "Bareilly",
    "Saharanpur",
    "Gorakhpur",
    "Faizabad",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Maunath Bhanjan",
    "Hapur",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Hardoi",
    "Fatehpur",
    "Raebareli",
    "Orai",
    "Sitapur",
    "Bahraich",
    "Modinagar",
    "Unnao",
    "Jaunpur",
    "Lakhimpur",
    "Pratapgarh",
    "Banda",
    "Pilibhit",
    "Hathras",
    "Mainpuri",
    "Etah",
    "Deoria",
    "Damoh",
    "Hamirpur",
    "Chitrakoot",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Bagpat",
    "Bahraich",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Ayodhya",
    "Azamgarh",
    "Bagpat",
    "Bahraich",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
  ];
}

class Uttarakhand {
  static List<String> cities = [
    "Dehradun",
    "Haridwar",
    "Rishikesh",
    "Nainital",
    "Rudrapur",
    "Kashipur",
    "Roorkee",
    "Haldwani",
    "Mussoorie",
    "Ramnagar",
    "Kotdwara",
    "Pithoragarh",
    "Manglaur",
    "Kichha",
    "Sitarganj",
    "Jaspur",
    "Bageshwar",
    "Mukteshwar",
    "Bazpur",
    "Didihat",
    "Devprayag",
    "Dogadda",
    "Gangotri",
    "Gopeshwar",
    "Gulaothi",
    "Jhabrera",
    "Joshimath",
    "Karanprayag",
    "Kashirampur",
    "Lansdowne",
    "Munsiari",
    "Pauri",
    "Pithoragarh",
    "Manglaur",
    "Kichha",
    "Sitarganj",
    "Jaspur",
    "Bageshwar",
    "Mukteshwar",
    "Bazpur",
    "Didihat",
    "Devprayag",
    "Dogadda",
    "Gangotri",
    "Gopeshwar",
    "Gulaothi",
    "Jhabrera",
    "Joshimath",
    "Karanprayag",
    "Kashirampur",
    "Lansdowne",
    "Munsiari",
    "Pauri",
    "Pithoragarh",
  ];
}

class WestBengal {
  static List<String> cities = [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Maheshtala",
    "Rajpur Sonarpur",
    "South Dumdum",
    "Gopalpur",
    "Bhatpara",
    "Panihati",
    "Kamarhati",
    "Bardhaman",
    "Kharagpur",
    "Barasat",
    "Alipurduar",
    "Baharampur",
    "Naihati",
    "Chandannagar",
    "Midnapore",
    "Haldia",
    "Krishnanagar",
    "Bankura",
    "Darjeeling",
    "Jalpaiguri",
    "Cooch Behar",
    "Malda",
    "Balurghat",
    "Santipur",
    "Ranaghat",
    "Raiganj",
    "Chakdaha",
    "Murshidabad",
    "Medinipur",
    "Bangaon",
    "Arambagh",
    "Tamluk",
    "Jangipur",
    "Suri",
    "Basirhat",
    "Nabadwip",
    "Diamond Harbour",
    "Darjeeling",
    "Jalpaiguri",
    "Cooch Behar",
    "Malda",
    "Balurghat",
    "Santipur",
    "Ranaghat",
    "Raiganj",
    "Chakdaha",
    "Murshidabad",
    "Medinipur",
    "Bangaon",
    "Arambagh",
    "Tamluk",
    "Jangipur",
    "Suri",
    "Basirhat",
    "Nabadwip",
    "Diamond Harbour",
  ];
}
class JammuKashmir {
static List<String> cities = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];}

class JammuAndKashmir {
  static List<String> cities = [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Kathua",
    "Sopore",
    "Bandipora",
    "Udhampur",
    "Rajouri",
    "Pulwama",
    "Kupwara",
    "Ganderbal",
    "Ramban",
    "Kishtwar",
    "Kargil",
    "Leh",
    "Poonch",
    "Shopian",
    "Budgam",
    "Doda",
    "Reasi",
    "Kulgam",
    "Samba",
    "Kargil",
    "Leh",
    "Poonch",
    "Shopian",
    "Budgam",
    "Doda",
    "Reasi",
    "Kulgam",
    "Samba",
    "Kargil",
    "Leh",
    "Poonch",
    "Shopian",
    "Budgam",
    "Doda",
    "Reasi",
    "Kulgam",
    "Samba",
  ];
}


  class Ladakh {
  static List<String> cities = [
  "Leh",
  "Kargil",
  "Diskit",
  "Nubra Valley",
  "Drass",
  "Hemis",
  "Lamayuru",
  "Alchi",
  "Likir",
  "Pangong",
  "Tso Moriri",
  "Changthang",
  "Nyoma",
  "Zanskar",
  "Padum",
  "Korzok",
  "Hanle",
  "Dah",
  "Magnetic Hill",
  "Khaltse",
  "Sankoo",
  "Nimu",
  "Stakna",
  "Rangdum",
  "Turtuk",
  "Fotu La",
  "Suru Valley",
  "Tingmosgang",
  "Phugtal",
  "Yuru Kabgyat",
  "Karsha",
  "Phyang",
  "Choglamsar",
  "Basgo",
  "Skurbuchan",
  "Dha",
  "Darchiks",
  "Panamik",
  "Tangtse",
  "Sakti",
  "Khaltsi",
  "Drokpa",
  "Lingshed",
  "Umling La",
  "Chumathang",
  "Sumda Chun",
  "Chusul",
  "Tegar",
  "Saspotse",
  "Liktsey",
  "Merak",
  "Tangyar",
  "Kongka Pass",
  "Takthok",
  "Tso Kar",
  "Phobrang",
  "Skyu",
  "Rumbak",
  "Stok",
  "Gya",
  "Turtot",
  "Tsaga",
  "Tsokar",
  "Skuru",
  "Ling",
  "Thiksay",
  "Matho",
  "Korzok",
  "Hanle",
  "Dah",
  "Magnetic Hill",
  "Khaltse",
  "Sankoo",
  "Nimu",
  "Stakna",
  "Rangdum",
  "Turtuk",
  "Fotu La",
  "Suru Valley",
  "Tingmosgang",
  "Phugtal",
  "Yuru Kabgyat",
  "Karsha",
  "Phyang",
  "Choglamsar",
  "Basgo",
  "Skurbuchan",
  "Dha",
  "Darchiks",
  "Panamik",
  "Tangtse",
  "Sakti",
  "Khaltsi",
  "Drokpa",
  "Lingshed",
  "Umling La",
  "Chumathang",
  "Sumda Chun",
  "Chusul",
  "Tegar",
  "Saspotse",
  "Liktsey",
  "Merak",
  "Tangyar",
  "Kongka Pass",
  "Takthok",
  "Tso Kar",
  "Phobrang",
  "Skyu",
  "Rumbak",
  "Stok",
  "Gya",
  "Turtot",
  "Tsaga",
  "Tsokar",
  "Skuru",
  "Ling",
  "Thiksay",
  "Matho",
  ];
  }

class Lakshadweep {
  static List<String> cities = [
    "Kavaratti",
    "Agatti",
    "Amini",
    "Andrott",
    "Kadmat",
    "Kalpeni",
    "Minicoy",
  ];
}

class Puducherry {
  static List<String> cities = [
    "Puducherry (Pondicherry)",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Ozhukarai",
    "Villianur",
    "Bahour",
    "Nettapakkam",
    "Ariyankuppam",
  ];
}

