class Malta {
  static List<String> localCouncils = [
    "Attard",
    "Balzan",
    "Birgu (Vittoriosa)",
    "Birkirkara",
    "Birżebbuġa",
    "Bormla (Cospicua)",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Għajnsielem",
    "Għarb",
    "Għargħur",
    "Għasri",
    "Għaxaq",
    "Gudja",
    "Gżira",
    "Ħamrun",
    "Iklin",
    "Isla (Senglea)",
    "Kalkara",
    "Kercem",
    "Kirkop",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Mellieħa",
    "Mosta",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Munxar",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pietà",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat",
    "Rabat (Gozo) (Victoria)",
    "Safi",
    "San Ġiljan (St. Julian's)",
    "San Ġwann",
    "San Lawrenz",
    "San Pawl il-Baħar (St. Paul's Bay)",
    "Santa Luċija",
    "Santa Venera",
    "Sannat",
    "Saint John (San Ġwann)",
    "Siggiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Xagħra",
    "Xewkija",
    "Xgħajra",
    "Żabbar",
    "Żebbuġ (Gozo)",
    "Żebbuġ (Malta)",
    "Żejtun",
    "Żurrieq"
  ];
}
