class CaboDelgado {
  static List<String> cities = [
    "Pemba",
    "Montepuez",
    "Mocímboa da Praia",
    "Quissanga",
    "Palma",
    "Macomia",
    "Ibo",
    "Mueda",
    "Ancuabe",
    "Balama",
    "Chiúre",
    "Mocímboa da Praia",
    "Mecúfi",
    "Metuge",
    "Meluco",
    "Mocímboa da Praia",
    "Nangade",
    "Mocímboa da Praia",
    "Pangane",
    "Mocímboa da Praia",
    "Pemba",
    "Quissanga",
    "Quionga",
    "Bilibiza",
    "Tandanhangue",
    "Macomia",
    "Mocímboa da Praia",
    "Mueda",
    "Nangade",
    "Pemba",
    "Quissanga",
    "Meluco",
    "Mocímboa da Praia",
    "Mocímboa da Praia",
    "Mocímboa da Praia",
    "Pangane",
    "Mocímboa da Praia",
    "Pemba",
    "Quissanga",
    "Macomia",
    "Ibo",
    "Mueda",
    "Nangade",
    "Mocímboa da Praia",
    "Pangane",
    "Mocímboa da Praia",
    "Pemba",
    "Quissanga",
    "Palma",
    "Macomia",
    "Ibo",
    "Mueda",
    "Nangade",
    "Ancuabe",
    "Balama",
    "Chiúre",
    "Mocímboa da Praia",
    "Mecúfi",
    "Metuge",
    "Meluco",
    "Pangane",
    "Mocímboa da Praia",
    "Pemba",
    "Quissanga",
    "Quionga",
    "Bilibiza",
    "Tandanhangue",
    "Macomia",
    "Mocímboa da Praia",
    "Mueda",
    "Nangade",
    "Pemba",
    "Quissanga",
    "Meluco",
    "Mocímboa da Praia",
    "Mocímboa da Praia",
    "Mocímboa da Praia",
    "Pangane",
    "Mocímboa da Praia",
  ];
}

class Gaza {
  static List<String> cities = [
    "Xai-Xai",
    "Chibuto",
    "Chókwè",
    "Manjacaze",
    "Bilene",
    "Guijá",
    "Mabalane",
    "Massingir",
    "Chicualacuala",
    "Chigubo",
    "Chókwè",
    "Chongoene",
    "Chibuto",
    "Chokwé",
    "Cumbana",
    "Mabalane",
    "Mandlakaze",
    "Mapai",
    "Massangena",
    "Massingir",
    "Massingir",
    "Massangena",
    "Massingir",
    "Mapai",
    "Massangena",
    "Massingir",
    "Mapai",
    "Massangena",
    "Mandlakaze",
    "Cumbana",
    "Mandlakaze",
    "Massingir",
    "Chicualacuala",
    "Chigubo",
    "Chibuto",
    "Chokwé",
    "Chókwè",
    "Chongoene",
  ];
}




class Manica {
  static List<String> cities = [
    "Chimoio",
    "Gondola",
    "Manica",
    "Macate",
    "Sussundenga",
    "Dombe",
    "Báruè",
    "Catandica",
    "Vanduzi",
    "Tambara",
    "Machaze",
    "Macossa",
    "Guro",
    "Gondola",
    "Mossurize",
    "Changara",
    "Mavonde",
    "Vila de Manica",
    "Vila de Báruè",
    "Vila de Macossa",
    "Vila de Vanduzi",
    "Vila de Tambara",
    "Vila de Machaze",
    "Vila de Guro",
    "Vila de Mossurize",
    "Vila de Changara",
    "Vila de Mavonde",
    "Vila de Dombe",
    "Vila de Gondola",
    "Chissuane",
    "Mucuio",
    "Macate",
    "Sussundenga",
    "Mavonde",
    "Dombe",
    "Gondola",
    "Catandica",
  ];
}


class MaputoCidade {
  static List<String> cities = [
    "Maputo",
    "Matola",
    "Katembe",
    "Marracuene",
    "Boane",
    "Namaacha",
    "Manhiça",
    "Moamba",
    "Magude",
    "Matutuíne",
  ];
}
class Inhambane {
  static List<String> cities = [
    "Inhambane",
    "Maxixe",
    "Vilankulo",
    "Quissico",
    "Inharrime",
    "Massinga",
    "Jangamo",
    "Homoíne",
    "Panda",
    "Govuro",
    "Funhalouro",
    "Zavala",
    "Praia do Tofo",
    "Praia da Barra",
    "Pomene",
    "Vilanculos",
    "Praia de Zavala",
    "Praia de Paindane",
    "Praia de Jangamo",
    "Praia do Bilene",
    "Praia do Rosário",
    "Praia da Zavora",
    "Praia dos Cocos",
    "Praia das Chocas",
    "Praia de Cumbuco",
    "Praia de Chitengo",
    "Praia de Guinjata",
    "Praia de Morrungulo",
    "Praia de Zongoene",
    "Praia de Inhassoro",
  ];
}

class Nampula {
  static List<String> cities = [
    "Nampula",
    "Nacala",
    "Angoche",
    "Nampula",
    "Monapo",
    "Ribaue",
    "Moma",
    "Mossuril",
    "Lalaua",
    "Meconta",
    "Murrupula",
    "Nacaroa",
    "Rapale",
    "Memba",
    "Mecubúri",
    "Malema",
    "Murrupula",
    "Monapo",
    "Mecubúri",
    "Meconta",
    "Mogovolas",
    "Lalaua",
    "Mecubúri",
    "Nacala-Porto",
    "Mossuril",
    "Mogincual",
    "Muecate",
    "Mogovolas",
    "Nacarôa",
    "Malema",
    "Mossuril",
    "Nacala-a-Velha",
    "Rapale",
    "Nacala-a-Velha",
    "Lalaua",
    "Nacala-Porto",
    "Nacarôa",
    "Mecubúri",
  ];
}

class Zambezia {
  static List<String> cities = [
    "Quelimane",
    "Gurúè",
    "Mocuba",
    "Nicoadala",
    "Namacurra",
    "Maganja da Costa",
    "Milange",
    "Alto Molócuè",
    "Mopeia",
    "Derre",
    "Lugela",
    "Luabo",
    "Chinde",
    "Namacurra",
    "Nampula",
    "Nicoadala",
    "Chinde",
    "Namacurra",
    "Mopeia",
    "Quelimane",
    "Mocuba",
    "Maganja da Costa",
    "Namacurra",
    "Mopeia",
    "Quelimane",
    "Gurúè",
    "Lugela",
    "Luabo",
    "Mocuba",
    "Derre",
    "Gile",
    "Gurúè",
    "Ile",
    "Inhassunge",
    "Lugela",
    "Lugela",
    "Luabo",
    "Macanga",
    "Maganja da Costa",
    "Maganja da Costa",
    "Malema",
    "Manganja",
    "Mocuba",
    "Mucubúri",
    "Namaviha",
    "Namarrói",
    "Namacurra",
    "Nante",
  ];
}

class Niassa {
  static List<String> cities = [
    "Cuamba",
    "Lichinga",
    "Mandimba",
    "Mavago",
    "Mecanhelas",
    "Metarica",
    "Muembe",
    "Ngauma",
    "Sanga",
    "Báruè",
    "Catur",
    "Marrupa",
    "Maulaua",
    "Mavago",
    "Mecanhelas",
    "Metarica",
    "M'to",
    "Muarua",
    "Nahache",
    "Nairoto",
    "Namacunde",
    "Nanhupo",
    "N'gaparua",
    "N'ganja",
    "N'golodemba",
    "N'guia",
    "N'guni",
    "N'guwala",
    "N'guri",
    "N'gurumia",
    "N'gueve",
    "N'gululo",
    "N'gunga",
    "N'halapua",
    "N'halonga",
    "N'hanga",
    "N'hatore",
    "N'hatumala",
    "N'havala",
    "N'henja",
    "N'himbis",
    "N'hungué",
    "N'hupe",
    "N'hurura",
    "N'japa",
    "N'juari",
    "N'kanda",
    "N'kuruco",
    "N'kute",
    "N'lange",
    "N'lava",
    "N'lengue",
    "N'lepiro",
    "N'lolo",
    "N'luepilira",
    "N'lumba",
    "N'lumina",
    "N'lumpu",
    "N'lumue",
    "N'lurma",
    "N'lussa",
    "N'litucula",
    "N'luzo",
    "N'madia",
    "N'madre",
    "N'mahocuma",
    "N'maiopa",
    "N'malava",
    "N'malira",
    "N'manga",
    "N'mango",
    "N'mangomani",
    "N'mangumbe",
    "N'mara",
    "N'mari",
    "N'marrara",
    "N'maua",
    "N'mauma",
    "N'maxixe",
    "N'mbuwe",
    "N'mbwa",
    "N'mele",
    "N'meleli",
    "N'meluzo",

    "N'mhalla",
    "N'muabue",
    "N'mua",
    "N'mua",
    "N'mualama",
    "N'muandiwanga",
    "N'muani",
    "N'muapela",
    "N'muece",
    "N'muecie",
    "N'muehu",
    "N'muelua",
    "N'muembo",
    "N'muenhe",
    "N'muenje",
    "N'muere",
    "N'mueu",
    "N'mueua",
    "N'mueuza",
    "N'muiavua",
    "N'muiaza",
    "N'muigire",
  ];
}
class Tete {
  static List<String> cities = [
    "Tete",
    "Angónia",
    "Cahora-Bassa",
    "Changara",
    "Chifunde",
    "Chiuta",
    "Doa",
    "Macanga",
    "Magoé",
    "Marara",
    "Mutarara",
    "Moatize",
    "Songo",
    "Tsangano",
    // Add more cities here if available
  ];
}

class Sofala {
  static List<String> cities = [
    "Beira",
    "Buzi",
    "Caia",
    "Chibabava",
    "Cheringoma",
    "Dondo",
    "Gorongosa",
    "Machanga",
    "Marromeu",
    "Muanza",
    "Mussorize",
    "Nhamatanda",
    "Nhamatanda",
    "Nhamatanda",
    "Vanduzi",
    "Nhamatanda",
    "Nhamatanda",
    "Nhamatanda",
    "Vanduzi",
    // Add more cities here if available
  ];
}
class Maputo {
  static List<String> cities = [
    "Maputo",
    "Matola",
    "Manhiça",
    "Moamba",
    "Namaacha",
    "Magude",
    "Boane",
    "Nonguéni",
    "Matutuine",
    "Marracuene",
    "Manhiça",
    "Moamba",
    // Add more cities here if available
  ];
}
