
class NorwayCities {
  static List<String> viken = [
    "Oslo",
    "Drammen",
    "Moss",
    "Sandefjord",
    "Tønsberg",
    "Fredrikstad",
    "Sarpsborg",
    "Halden",
    "Lillestrøm",
    "Ski",
    "Askim",
    "Drøbak",
    "Holmestrand",
    "Notodden",
    "Fetsund",
    "Ås",
    "Svelvik",
    "Langesund",
    "Åsgårdstrand",
    "Sørlandsparken",
    "Kongsvinger",
    "Son",
    "Hønefoss",
  ];

  static List<String> oslo = [
    "Oslo",
  ];

  static List<String> innlandet = [
    "Hamar",
    "Gjøvik",
    "Lillehammer",
    "Kongsvinger",
    "Otta",
    "Brumunddal",
    "Vinstra",
    "Fagernes",
    "Kirkenes",
    "Ørnes",
    "Eidsvoll",
    "Elverum",
    "Jessheim",
    "Tynset",
  ];

  static List<String> vestfoldOgTelemark = [
    "Skien",
    "Porsgrunn",
    "Larvik",
    "Sandefjord",
    "Tønsberg",
    "Horten",
    "Færder",
    "Holmestrand",
    "Notodden",
    "Tvedestrand",
    "Langesund",
    "Stokmarknes",
    "Straume",
    "Svelvik",
    "Kragerø",
    "Rjukan",
    "Bamble",
  ];

  static List<String> agder = [
    "Kristiansand",
    "Arendal",
    "Mandal",
    "Flekkefjord",
    "Grimstad",
    "Farsund",
    "Vennesla",
    "Grimstad",
    "Lyngdal",
    "Sørlandsparken",
    "Risør",
    "Evje",
    "Vågsbygd",
  ];

  static List<String> rogaland = [
    "Stavanger",
    "Sandnes",
    "Haugesund",
    "Egersund",
    "Kopervik",
    "Åkrehamn",
    "Sauda",
    "Bryne",
    "Jørpeland",
    "Knarvik",
    "Straume",
    "Sandnesjøen",
    "Skudeneshavn",
    "Kopervik",
    "Åkrehamn",
  ];

  static List<String> vestland = [
    "Bergen",
    "Ålesund",
    "Kristiansund",
    "Molde",
    "Harstad",
    "Sogndal",
    "Volda",
    "Brønnøysund",
    "Ulsteinvik",
    "Sogndalsfjøra",
    "Stord",
    "Tvedestrand",
    "Åsgårdstrand",
    "Sørlandsparken",
    "Florø",
    "Ørsta",
  ];

  static List<String> mOgR = [
    "Ålesund",
    "Molde",
    "Kristiansund",
    "Brønnøysund",
    "Ulsteinvik",
    "Sogndalsfjøra",
    "Stord",
    "Tvedestrand",
    "Åsgårdstrand",
    "Sørlandsparken",
    "Ørsta",
    "Vanylven",
    "Stranda",
  ];

  static List<String> trondelag = [
  "Trondheim",
  "Steinkjer",
  "Namsos",
  "Røros",
  "Verdal",
  "Stjørdalshalsen",
  "Levanger",
  "Malvik",
  "Fosen",
  "Sørlandsparken",
  "Orkanger",
  "Oppdal",
  "Fosen",
  ];

  static List<String> nordland = [
    "Bodø",
    "Narvik",
    "Mo i Rana",
    "Mosjøen",
    "Sandnessjøen",
    "Fauske",
    "Leknes",
    "Svolvær",
    "Stokmarknes",
    "Honningsvåg",
    "Straume",
    "Sandnesjøen",
    "Melbu",
    "Sortland",
    "Stokmarknes",
    "Svolvær",
  ];

  static List<String> tromsOgFinnmark = [
    "Tromsø",
    "Hammerfest",
    "Alta",
    "Kirkenes",
    "Vadsø",
    "Harstad",
    "Narvik",
    "Tana",
    "Honningsvåg",
    "Knarvik",
    "Straume",
    "Sandnesjøen",
    "Stokmarknes",
    "Svolvær",
    "Bardufoss",
    "Vardø",
    "Mo i Rana",
    "Sortland",
    "Stokmarknes",
    "Svolvær",
    "Vadso",
    "Karasjok",
    "Lakselv",
  ];
}
