class PunjabPakistan {
  static List<String> cities = [
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sheikhupura",
    "Jhang",
    "Sahiwal",
    "Okara",
    "Gujrat",
    "Kasur",
    "Rahim Yar Khan",
    "Dera Ghazi Khan",
    "Muzaffargarh",
    "Vehari",
    "Khanewal",
    "Chiniot",
    "Narowal",
    "Mandi Bahauddin",
    "Pakpattan",
    "Toba Tek Singh",
    "Hafizabad",
    "Kamalia",
    "Muridke",
    "Chishtian",
    "Chunian",
    "Burewala",
  ];
}

class Sindh {
  static List<String> cities = [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpur Khas",
    "Khairpur",
    "Jacobabad",
    "Shikarpur",
    "Dadu",
    "Badin",
    "Thatta",
    "Tando Allahyar",
    "Sanghar",
    "Kashmore",
    "Ghotki",
    "Matiari",
    "Umerkot",
    "Jamshoro",
    "Naushahro Feroze",
    "Mirpur Mathelo",
    "Kotri",
    "Shahdadkot",
    "Mithi",
    "Rohri",
    "Ratodero",
    "Moro",
    "Kot Diji",
  ];
}

class KhyberPakhtunkhwa {
  static List<String> cities = [
    "Peshawar",
    "Abbottabad",
    "Mardan",
    "Mingora (Swat)",
    "Kohat",
    "Haripur",
    "Mansehra",
    "Dera Ismail Khan",
    "Charsadda",
    "Nowshera",
    "Swabi",
    "Bannu",
    "Batkhela",
    "Chitral",
    "Hangu",
    "Lakki Marwat",
    "Tank",
    "Upper Dir",
    "Lower Dir",
    "Malakand",
    "Shabqadar",
    "Risalpur",
    "Parachinar",
    "Timergara",
    "Takht Bhai",
    "Dargai",
    "Dir",
    "Shangla",
    "Drosh",
  ];
}

class Balochistan {
  static List<String> cities = [
    "Quetta",
    "Gwadar",
    "Turbat",
    "Khuzdar",
    "Chaman",
    "Sibi",
    "Zhob",
    "Loralai",
    "Mastung",
    "Nushki",
    "Kalat",
    "Kharan",
    "Panjgur",
    "Lasbela",
    "Dera Bugti",
    "Jiwani",
    "Washuk",
    "Awaran",
    "Barkhan",
    "Musa Khel",
    "Kachhi (Bolan)",
    "Ziarat",
    "Pasni",
    "Kech",
    "Dalbandin",
    "Chagai",
    "Harnai",
    "Sohbatpur",
    "Khanozai",
    "Surab",
  ];
}

class IslamabadCapitalTerritory {
  static List<String> cities = [
    "Islamabad (Capital)",
  ];
}

class GilgitBaltistan {
  static List<String> cities = [
    "Gilgit",
    "Skardu",
    "Chilas",
    "Ghizer",
    "Hunza",
    "Nagar",
    "Gupis",
    "Astore",
    "Khaplu",
    "Shigar",
    "Danyore",
    "Gahkuch",
    "Gilgit Sadpara",
    "Jutial",
    "Karimabad",
    "Shangla",
    "Thole",
    "Tolti",
    "Yasin",
    "Gultari",
    "Rondu",
    "Baltit",
    "Kharmang",
    "Chorbat",
    "Sher Qila",
    "Gahar",
    "Kargah",
  ];
}
