class Pampanga {
  static List<String> citiesAndTowns = [
    "Angeles City (Highly Urbanized)",
    "Mabalacat City (Component City)",
    "San Fernando City (Capital) (Highly Urbanized)",
    "Apalit",
    "Arayat",
    "Bacolor",
    "Candaba",
    "Floridablanca",
    "GuaGua",
    "Lubao",
    "Macabebe",
    "Magalang",
    "Masantol",
    "Mexico",
    "Minalin",
    "Porac",
    "San Luis",
    "San Simon",
    "Santa Ana",
    "Santa Rita",
    "Santo Tomas",
    "Sasmuan",
  ];
}

class Pangasinan {
  static List<String> citiesAndTowns = [
    "Alaminos City (Component City)",
    "Dagupan City (Highly Urbanized)",
    "San Carlos City (Component City)",
    "Urdaneta City (Component City)",
    "Agno",
    "Aguilar",
    "Alcala",
    "Anda",
    "Asingan",
    "Balungao",
    "Bani",
    "Basista",
    "Bautista",
    "Bayambang",
    "Binalonan",
    "Binmaley",
    "Bolinao",
    "Bugallon",
    "Burgos",
    "Calasiao",
    "Dasol",
    "Infanta",
    "Labrador",
    "Laoac",
    "Lingayen (Capital)",
    "Mabini",
    "Malasiqui",
    "Manaoag",
    "Mangaldan",
    "Mangatarem",
    "Mapandan",
    "Natividad",
    "Pozorrubio",
    "Rosales",
    "San Fabian",
    "San Jacinto",
    "San Manuel",
    "San Nicolas",
    "San Quintin",
    "Santa Barbara",
    "Santa Maria",
    "Santo Tomas",
    "Sison",
    "Sual",
    "Tayug",
    "Umingan",
    "Urbiztondo",
    "Villasis",
  ];
}

// Continue with other provinces...
class Quezon {
  static List<String> citiesAndTowns = [
    "Lucena City (Highly Urbanized)",
    "Tayabas City (Component City)",
    "Candelaria",
    "Dolores",
    "Lucban",
    "Lucena City (Capital)",
    "Pagbilao",
    "Mauban",
    "Sampaloc",
    "San Antonio",
    "San Francisco",
    "Sariaya",
    "Tiaong",
  ];
}

class Quirino {
  static List<String> citiesAndTowns = [
    "Aglipay",
    "Cabarroguis (Capital)",
    "Diffun",
    "Maddela",
    "Nagtipunan",
    "Saguday",
  ];
}

class Rizal {
  static List<String> citiesAndTowns = [
    "Antipolo City (Highly Urbanized)",
    "Angono",
    "Baras",
    "Binangonan",
    "Cainta",
    "Cardona",
    "Jalajala",
    "Morong",
    "Pililla",
    "Rodriguez (Montalban)",
    "San Mateo",
    "Tanay",
    "Taytay",
    "Teresa",
  ];
}

class Romblon {
  static List<String> citiesAndTowns = [
    "Alcantara",
    "Banton",
    "Cajidiocan",
    "Calatrava",
    "Concepcion",
    "Corcuera",
    "Ferrol",
    "Looc",
    "Magdiwang",
    "Odiongan (Capital)",
    "Romblon (Capital)",
    "San Agustin",
    "San Andres",
    "San Fernando",
    "San Jose",
    "Santa Fe",
  ];
}

class Samar {
  static List<String> citiesAndTowns = [
    "Calbayog City (Highly Urbanized)",
    "Catbalogan City (Highly Urbanized)",
    "Almagro",
    "Basey",
    "Calbiga",
    "Daram",
    "Gandara",
    "Hinabangan",
    "Jiabong",
    "Marabut",
    "Matuguinao",
    "Motiong",
    "Pagsanghan",
    "Paranas (Wright)",
    "Pinabacdao",
    "San Jorge",
    "San Jose de Buan",
    "San Sebastian",
    "Santa Margarita",
    "Santa Rita",
    "Santo Niño",
    "Tagapul-an",
    "Talalora",
    "Tarangnan",
    "Villareal",
    "Zumarraga",
  ];
}

// Continue with other provinces...
class Sarangani {
  static List<String> citiesAndTowns = [
    "Alabel (Capital)",
    "Glan",
    "Kiamba",
    "Maasim",
    "Maitum",
    "Malapatan",
  ];
}

class Siquijor {
  static List<String> citiesAndTowns = [
    "Enrique Villanueva",
    "Larena",
    "Lazi",
    "Maria",
    "San Juan (Cabecera)",
    "Siquijor (Capital)",
  ];
}

class Sorsogon {
  static List<String> citiesAndTowns = [
    "Sorsogon City (Highly Urbanized)",
    "Barcelona",
    "Bulan",
    "Bulusan",
    "Casiguran",
    "Castilla",
    "Donsol",
    "Gubat",
    "Irosin",
    "Juban",
    "Magallanes",
    "Matnog",
    "Pilar",
    "Prieto Diaz",
    "Santa Magdalena",
  ];
}

class SouthCotabato {
  static List<String> citiesAndTowns = [
    "Koronadal City (Highly Urbanized)",
    "Banga",
    "Lake Sebu",
    "Norala",
    "Polomolok",
    "Santo Niño",
    "Surallah",
    "T'boli",
    "Tampakan",
    "Tupi",
  ];
}

class SouthernLeyte {
  static List<String> citiesAndTowns = [
    "Maasin City (Highly Urbanized)",
    "Anahawan",
    "Bontoc",
    "Hinunangan",
    "Hinundayan",
    "Libagon",
    "Liloan",
    "Limasawa",
    "Macrohon",
    "Malitbog",
    "Padre Burgos",
    "Pintuyan",
    "Saint Bernard",
    "San Francisco",
    "San Juan (Cabalian)",
    "San Ricardo",
    "Silago",
    "Sogod",
    "Tomas Oppus",
  ];
}

class SultanKudarat {
  static List<String> citiesAndTowns = [
    "Isulan (Capital)",
    "Bagumbayan",
    "Columbio",
    "Esperanza",
    "Kalamansig",
    "Lambayong (Mariano Marcos)",
    "Lebak",
    "Lutayan",
    "Palimbang",
    "President Quirino",
    "Senator Ninoy Aquino",
  ];
}

class Sulu {
  static List<String> citiesAndTowns = [
    "Jolo (Capital)",
    "Indanan",
    "Kalingalan Caluang",
    "Lugus",
    "Luuk",
    "Maimbung",
    "Old Panamao",
    "Omar",
    "Pandami",
    "Panglima Estino (New Panamao)",
    "Pangutaran",
    "Parang",
    "Pata",
    "Patikul",
    "Siasi",
    "Talipao",
    "Tapul",
    "Tongkil",
  ];
}

class SurigaoDelNorte {
  static List<String> citiesAndTowns = [
    "Surigao City (Highly Urbanized)",
    "Alegria",
    "Bacuag",
    "Basilisa (Rizal)",
    "Burgos",
    "Claver",
    "Dapa",
    "Del Carmen",
    "General Luna",
    "Gigaquit",
    "Mainit",
    "Malimono",
    "Pilar",
    "Placer",
    "San Benito",
    "San Francisco (Anao-Aon)",
    "San Isidro",
    "Santa Monica (Sapao)",
    "Sison",
    "Socorro",
    "Tagana-an",
    "Tubod",
  ];
}

class SurigaoDelSur {
  static List<String> citiesAndTowns = [
    "Tandag City (Highly Urbanized)",
    "Barobo",
    "Bayabas",
    "Cagwait",
    "Cantilan",
    "Carmen",
    "Carrascal",
    "Cortes",
    "Hinatuan",
    "Lanuza",
    "Lianga",
    "Lingig",
    "Madrid",
    "Marihatag",
    "San Agustin",
    "San Miguel",
    "Tagbina",
    "Tago",
  ];
}

class Tarlac {
  static List<String> citiesAndTowns = [
    "Tarlac City (Highly Urbanized)",
    "Anao",
    "Bamban",
    "Camiling",
    "Capas",
    "Concepcion",
    "Gerona",
    "La Paz",
    "Mayantoc",
    "Moncada",
    "Paniqui",
    "Pura",
    "Ramos",
    "San Clemente",
    "San Jose",
    "San Manuel",
    "Santa Ignacia",
    "Victoria",
  ];
}

class TawiTawi {
  static List<String> citiesAndTowns = [
    "Bongao (Capital)",
    "Languyan",
    "Mapun (Cagayan de Tawi-Tawi)",
    "Panglima Sugala (Balimbing)",
    "Sapa-Sapa",
    "Sibutu",
    "Simunul",
    "Sitangkai",
    "South Ubian",
    "Tandubas",
    "Turtle Islands (Taganak)",
  ];
}

class Zambales {
  static List<String> citiesAndTowns = [
    "Olongapo City (Highly Urbanized)",
    "Botolan",
    "Cabangan",
    "Candelaria",
    "Castillejos",
    "Iba (Capital)",
    "Masinloc",
    "Palauig",
    "San Antonio",
    "San Felipe",
    "San Marcelino",
    "San Narciso",
    "Santa Cruz",
  ];
}

class ZamboangaDelNorte {
  static List<String> citiesAndTowns = [
    "Dipolog City (Highly Urbanized)",
    "Dapitan City (Highly Urbanized)",
    "Balingoan",
    "Baliguian",
    "Godod",
    "Gutalac",
    "Jose Dalman (Ponot)",
    "Kalawit",
    "Katipunan",
    "La Libertad",
    "Labason",
    "Liloy",
    "Manukan",
    "Mutia",
    "Piñan (New Piñan)",
    "Polanco (Palanco)",
    "President Manuel A. Roxas",
    "Rizal",
    "Salug",
    "Sergio Osmeña Sr.",
    "Siayan",
    "Sibuco",
    "Sindangan",
    "Siocon",
    "Sirawai",
    "Sibuco",
  ];
}

class Camiguin {
  static List<String> citiesAndTowns = [
    "Catarman",
    "Guinsiliban",
    "Mahinog",
    "Mambajao (Capital)",
  ];
}

class Capiz {
  static List<String> citiesAndTowns = [
    "Roxas City (Highly Urbanized)",
    "Cuartero",
    "Dao",
    "Dumalag",
    "Dumarao",
    "Ivisan",
    "Jamindan",
    "Maayon",
    "Mambusao",
    "Panay",
    "Panitan",
    "Pilar",
    "Pontevedra",
    "President Roxas",
    "Sapi-an",
    "Sigma",
    "Tapaz",
  ];
}

class Catanduanes {
  static List<String> citiesAndTowns = [
    "Virac (Capital)",
    "Bagamanoc",
    "Baras",
    "Bato",
    "Caramoran",
    "Gigmoto",
    "Pandan",
    "Panganiban",
    "San Andres",
    "San Miguel",
    "Viga",
  ];
}

class Cavite {
  static List<String> citiesAndTowns = [
    "Bacoor City (Highly Urbanized)",
    "Cavite City (Highly Urbanized)",
    "Dasmariñas City (Component City)",
    "Tagaytay City (Component City)",
    "Trece Martires City (Capital)",
    "Alfonso",
    "Amadeo",
    "Bailen",
    "Carmona",
    "General Emilio Aguinaldo (Bailen)",
    "General Mariano Alvarez",
    "General Trias",
    "Imus City (Component City)",
    "Indang",
    "Kawit",
    "Magallanes",
    "Maragondon",
    "Mendez",
    "Naic",
    "Noveleta",
    "Rosario",
    "Silang",
    "Tanza",
    "Ternate",
  ];
}

class Cebu {
  static List<String> citiesAndTowns = [
    "Cebu City (Highly Urbanized)",
    "Carcar City (Component City)",
    "Danao City (Component City)",
    "Lapu-Lapu City (Highly Urbanized)",
    "Mandaue City (Highly Urbanized)",
    "Naga City (Component City)",
    "Talisay City (Component City)",
    "Toledo City (Component City)",
    "Alcantara",
    "Alcoy",
    "Alegria",
    "Aloguinsan",
    "Argao",
    "Asturias",
    "Badian",
    "Balamban",
    "Bantayan",
    "Barili",
    "Bogo City (Component City)",
    "Boljoon",
    "Borbon",
    "Carmen",
    "Catmon",
    "Compostela",
    "Consolacion",
    "Cordoba",
    "Daanbantayan",
    "Dalaguete",
    "Dumanjug",
    "Ginatilan",
    "Liloan",
    "Madridejos",
    "Malabuyoc",
    "Medellin",
    "Minglanilla",
    "Moalboal",
    "Oslob",
    "Pilar",
    "Pinamungajan",
    "Poro",
    "Ronda",
    "Samboan",
    "San Fernando",
    "San Francisco",
    "San Remigio",
    "Santa Fe",
    "Santander",
    "Sibonga",
    "Sogod",
    "Tabogon",
    "Tabuelan",
    "Tuburan",
    "Tudela",
  ];
}

class CompostelaValley {
  static List<String> citiesAndTowns = [
    "Nabunturan (Capital)",
    "Compostela",
    "Laak (San Vicente)",
    "Mabini (Doña Alicia)",
    "Maco",
    "Maragusan (San Mariano)",
    "Mawab",
    "Monkayo",
    "Montevista",
    "New Bataan",
    "Pantukan",
  ];
}

class Cotabato {
  static List<String> citiesAndTowns = [
    "Kidapawan City (Highly Urbanized)",
    "Alamada",
    "Aleosan",
    "Antipas",
    "Arakan",
    "Banisilan",
    "Carmen",
    "Kabacan",
    "Libungan",
    "M'lang",
    "Magpet",
    "Makilala",
    "Matalam",
    "Midsayap",
    "Pigkawayan",
    "Pikit",
    "President Roxas",
    "Tulunan",
  ];
}

class DavaoDeOro {
  static List<String> citiesAndTowns = [
    "Nabunturan (Capital)",
    "Compostela",
    "Laak (San Vicente)",
    "Mabini (Doña Alicia)",
    "Maco",
    "Maragusan (San Mariano)",
    "Mawab",
    "Monkayo",
    "Montevista",
    "New Bataan",
    "Pantukan",
  ];
}

class DavaoDelNorte {
  static List<String> citiesAndTowns = [
    "Tagum City (Highly Urbanized)",
    "Island Garden City of Samal (Component City)",
    "Panabo City (Highly Urbanized)",
    "Nabunturan (Capital)",
    "Asuncion (Saug)",
    "Braulio E. Dujali",
    "Carmen",
    "Kapalong",
    "New Corella",
    "San Isidro",
    "Santo Tomas",
    "Talaingod",
  ];
}

class DavaoDelSur {
  static List<String> citiesAndTowns = [
    "Digos City (Highly Urbanized)",
    "Bansalan",
    "Don Marcelino",
    "Hagonoy",
    "Jose Abad Santos (Trinidad)",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Matanao",
    "Padada",
    "Santa Cruz (Capital)",
    "Sulop",
  ];
}

class DavaoOccidental {
  static List<String> citiesAndTowns = [
    "Malita (Capital)",
    "Don Marcelino",
    "Jose Abad Santos (Trinidad)",
    "Sarangani",
  ];
}

class DavaoOriental {
  static List<String> citiesAndTowns = [
    "Mati City (Capital) (Highly Urbanized)",
    "Baganga",
    "Banaybanay",
    "Boston",
    "Caraga",
    "Cateel",
    "Governor Generoso",
    "Lupon",
    "Manay",
    "San Isidro",
    "Tarragona",
  ];
}

class DinagatIslands {
  static List<String> citiesAndTowns = [
    "Basilisa (Rizal) (Capital)",
    "Cagdianao",
    "Dinagat",
    "Libjo (Albor)",
    "Loreto",
    "San Jose",
    "Tubajon",
  ];
}

class EasternSamar {
  static List<String> citiesAndTowns = [
    "Borongan City (Highly Urbanized)",
    "Arteche",
    "Balangiga",
    "Balangkayan",
    "Can-avid",
    "Dolores",
    "General MacArthur",
    "Giporlos",
    "Guiuan",
    "Hernani",
    "Jipapad",
    "Lawaan",
    "Llorente",
    "Maslog",
    "Maydolong",
    "Mercedes",
    "Oras",
    "Quinapondan",
    "Salcedo",
    "San Julian",
    "San Policarpo",
    "Sulat",
    "Taft",
  ];
}

class Guimaras {
  static List<String> citiesAndTowns = [
    "Jordan (Capital)",
    "Buenavista",
    "Nueva Valencia",
    "San Lorenzo",
    "Sibunag",
  ];
}

class Ifugao {
  static List<String> citiesAndTowns = [
    "Lagawe (Capital)",
    "Aguinaldo",
    "Alfonso Lista (Potia)",
    "Asipulo",
    "Banaue",
    "Hingyon",
    "Hungduan",
    "Kiangan",
    "Lamut",
    "Mayoyao",
    "Tinoc",
  ];
}

class IlocosNorte {
  static List<String> citiesAndTowns = [
    "Laoag City (Highly Urbanized)",
    "Batac City (Component City)",
    "Badoc",
    "Bangui",
    "Banna (Espiritu)",
    "Burgos",
    "Carasi",
    "Currimao",
    "Dingras",
    "Dumalneg",
    "Marcos",
    "Nueva Era",
    "Pagudpud",
    "Paoay",
    "Pasuquin",
    "Piddig",
    "Pinili",
    "San Nicolas",
    "Sarrat",
    "Solsona",
    "Vintar",
  ];
}

class IlocosSur {
  static List<String> citiesAndTowns = [
    "Vigan City (Highly Urbanized)",
    "Candon City (Component City)",
    "Alilem",
    "Banayoyo",
    "Bantay",
    "Burgos",
    "Cabugao",
    "Caoayan",
    "Cervantes",
    "Galimuyod",
    "Gregorio del Pilar (Concepcion)",
    "Lidlidda",
    "Magsingal",
    "Nagbukel",
    "Narvacan",
    "Quirino (Angkaki)",
    "Salcedo (Baugen)",
    "San Emilio",
    "San Esteban",
    "San Ildefonso",
    "San Juan",
    "San Vicente",
    "Santa",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Domingo",
    "Sigay",
    "Sinait",
    "Sugpon",
    "Suyo",
    "Tagudin",
  ];
}

class Iloilo {
  static List<String> citiesAndTowns = [
    "Iloilo City (Highly Urbanized)",
    "Passi City (Component City)",
    "Ajuy",
    "Alimodian",
    "Anilao",
    "Badiangan",
    "Balasan",
    "Banate",
    "Barotac Nuevo",
    "Barotac Viejo",
    "Batad",
    "Bingawan",
    "Cabatuan",
    "Calinog",
    "Carles",
    "Concepcion",
    "Dingle",
    "Duenas",
    "Dumangas",
    "Estancia",
    "Guimbal",
    "Igbaras",
    "Janiuay",
    "Lambunao",
    "Leganes",
    "Lemery",
    "Leon",
    "Maasin",
    "Miagao",
    "Mina",
    "New Lucena",
    "Oton",
    "Pavia",
    "Pototan",
    "San Dionisio",
    "San Enrique",
    "San Joaquin",
    "San Miguel",
    "San Rafael",
    "Santa Barbara",
    "Sara",
    "Tigbauan",
    "Tubungan",
    "Zarraga",
  ];
}

class Isabela {
  static List<String> citiesAndTowns = [
    "Ilagan City (Capital) (Highly Urbanized)",
    "Cauayan City (Component City)",
    "Alicia",
    "Angadanan",
    "Aurora",
    "Benito Soliven",
    "Burgos",
    "Cabagan",
    "Cabatuan",
    "Cordon",
    "Delfin Albano (Magsaysay)",
    "Dinapigue",
    "Divilacan",
    "Echague",
    "Gamu",
    "Jones",
    "Luna",
    "Maconacon",
    "Mallig",
    "Naguilian",
    "Palanan",
    "Quezon",
    "Quirino",
    "Ramon",
    "Reina Mercedes",
    "Roxas",
    "San Agustin",
    "San Guillermo",
    "San Isidro",
    "San Manuel",
    "San Mariano",
    "San Mateo",
    "San Pablo",
    "Santa Maria",
    "Santiago City (Component City)",
    "Santo Tomas",
    "Tumauini",
  ];
}
class ZamboangaDelSur {
  static List<String> citiesAndTowns = [
    "Pagadian City (Highly Urbanized)",
    "Dapitan City (Component City)",
    "Dipolog City (Highly Urbanized)",
    "Aurora",
    "Bayog",
    "Dimataling",
    "Dinas",
    "Dumalinao",
    "Dumingag",
    "Guipos",
    "Josefina",
    "Kumalarang",
    "Labangan",
    "Lakewood",
    "Lapuyan",
    "Mahayag",
    "Margosatubig",
    "Midsalip",
    "Molave",
    "Pitogo",
    "Ramon Magsaysay (Liargo)",
    "San Miguel",
    "San Pablo",
    "Sominot",
    "Tabina",
    "Tambulig",
    "Tigbao",
    "Tukuran",
    "Vincenzo A. Sagun",
    "Zamboanga City (Component City)",
  ];
}

class Kalinga {
  static List<String> citiesAndTowns = [
    "Tabuk City (Highly Urbanized)",
    "Balbalan",
    "Lubuagan",
    "Pasil",
    "Pinukpuk",
    "Rizal (Liwan)",
    "Tanudan",
    "Tinglayan",
  ];
}

class LaUnionP {
  static List<String> citiesAndTowns = [
    "San Fernando City (Highly Urbanized)",
    "Agoo",
    "Aringay",
    "Bacnotan",
    "Bagulin",
    "Balaoan",
    "Bangar",
    "Bauang",
    "Burgos",
    "Caba",
    "Luna",
    "Naguilian",
    "Pugo",
    "Rosario",
    "San Gabriel",
    "San Juan",
    "Santo Tomas",
    "Santol",
    "Sudipen",
    "Tubao",
  ];
}

class Laguna {
  static List<String> citiesAndTowns = [
    "Biñan City (Component City)",
    "Calamba City (Component City)",
    "San Pablo City (Component City)",
    "Santa Rosa City (Component City)",
    "Alaminos",
    "Bay",
    "Cabuyao City (Component City)",
    "Calauan",
    "Cavinti",
    "Famy",
    "Kalayaan",
    "Liliw",
    "Los Baños",
    "Luisiana",
    "Lumban",
    "Mabitac",
    "Magdalena",
    "Majayjay",
    "Nagcarlan",
    "Paete",
    "Pagsanjan",
    "Pakil",
    "Pangil",
    "Pila",
    "Rizal",
    "San Pedro City (Component City)",
    "Santa Cruz (Capital)",
    "Santa Maria",
    "Siniloan",
    "Victoria",
  ];
}

class LanaoDelNorte {
  static List<String> citiesAndTowns = [
    "Iligan City (Highly Urbanized)",
    "Bacolod",
    "Baloi",
    "Baroy",
    "Kapatagan",
    "Kauswagan",
    "Kolambugan",
    "Lala",
    "Linamon",
    "Magsaysay",
    "Maigo",
    "Matungao",
    "Munai",
    "Nunungan",
    "Pantao Ragat",
    "Pantar",
    "Poona Piagapo",
    "Salvador",
    "Sapad",
    "Sultan Naga Dimaporo (Karomatan)",
    "Tagoloan",
    "Tangcal",
    "Tubod (Capital)",
  ];
}

class LanaoDelSur {
  static List<String> citiesAndTowns = [
    "Marawi City (Highly Urbanized)",
    "Bacolod-Kalawi (Bacolod-Grande)",
    "Balabagan",
    "Balindong (Watu)",
    "Bayang",
    "Binidayan",
    "Buadiposo-Buntong",
    "Bubong",
    "Butig",
    "Calanogas",
    "Ditsaan-Ramain",
    "Ganassi",
    "Kapai",
    "Kapatagan",
    "Lumba-Bayabao (Maguing)",
    "Lumbaca-Unayan",
    "Lumbatan",
    "Lumbayanague",
    "Madalum",
    "Madamba (Gata)",
    "Maguing (Lumba-Bayabao)",
    "Malabang",
    "Marantao",
    "Marogong",
    "Masiu",
    "Mulondo",
    "Pagayawan (Tatarikan)",
    "Piagapo",
    "Picong (Sultan Gumander)",
    "Poona Bayabao (Gata)",
    "Pualas",
    "Saguiaran",
    "Sultan Dumalondong",
    "Tagoloan II",
    "Tamparan",
    "Taraka",
    "Tubaran",
    "Tugaya",
    "Wao",
  ];
}

class Leyte {
  static List<String> citiesAndTowns = [
    "Ormoc City (Highly Urbanized)",
    "Tacloban City (Highly Urbanized)",
    "Abuyog",
    "Alangalang",
    "Albuera",
    "Babatngon",
    "Barugo",
    "Bato",
    "Baybay City (Component City)",
    "Burauen",
    "Calubian",
    "Capoocan",
    "Carigara",
    "Dagami",
    "Dulag",
    "Hilongos",
    "Hindang",
    "Inopacan",
    "Isabel",
    "Jaro",
    "Javier (Bugho)",
    "Julita",
    "Kananga",
    "La Paz",
    "Leyte",
    "MacArthur",
    "Mahaplag",
    "Matag-ob",
    "Matalom",
    "Mayorga",
    "Merida",
    "Palo",
    "Palompon",
    "Pastrana",
    "San Isidro",
    "San Miguel",
    "Santa Fe",
    "Tabango",
    "Tabontabon",
    "Tanauan",
    "Tolosa",
    "Tunga",
    "Villaba",
  ];
}

class Maguindanao {
  static List<String> citiesAndTowns = [
    "Cotabato City (Highly Urbanized)",
    "Ampatuan",
    "Barira",
    "Buldon",
    "Buluan (Capital)",
    "Datu Abdullah Sangki",
    "Datu Anggal Midtimbang",
    "Datu Blah T. Sinsuat",
    "Datu Hoffer Ampatuan",
    "Datu Montawal (Pagagawan)",
    "Datu Odin Sinsuat (Dinaig)",
    "Datu Paglas",
    "Datu Piang (Dulawan)",
    "Datu Salibo",
    "Datu Saudi-Ampatuan",
    "Datu Unsay",
    "General Salipada K. Pendatun",
    "Guindulungan",
    "Kabuntalan (Tumbao)",
    "Mamasapano",
    "Mangudadatu",
    "Matanog",
    "Northern Kabuntalan",
    "Pagalungan",
    "Paglat",
    "Pandag",
    "Parang",
    "Rajah Buayan",
    "Shariff Aguak (Maganoy) (Capital)",
    "Shariff Saydona Mustapha",
    "South Upi",
    "Sultan Kudarat (Nuling)",
    "Sultan Mastura",
    "Sultan sa Barongis (Lambayong)",
    "Talayan",
    "Talitay",
    "Upi",
  ];
}

class Marinduque {
  static List<String> citiesAndTowns = [
    "Boac (Capital)",
    "Buenavista",
    "Gasan",
    "Mogpog",
    "Santa Cruz",
    "Torrijos",
  ];
}

class Masbate {
  static List<String> citiesAndTowns = [
    "Masbate City (Highly Urbanized)",
    "Aroroy",
    "Baleno",
    "Balud",
    "Batuan",
    "Cataingan",
    "Cawayan",
    "Claveria",
    "Dimasalang",
    "Esperanza",
    "Mandaon",
    "Milagros",
    "Mobo",
    "Monreal",
    "Palanas",
    "Pio V. Corpuz",
    "Placer",
    "San Fernando",
    "San Jacinto",
    "San Pascual",
    "Uson",
  ];
}

class MisamisOccidental {
  static List<String> citiesAndTowns = [
    "Oroquieta City (Highly Urbanized)",
    "Tangub City (Highly Urbanized)",
    "Aloran",
    "Baliangao",
    "Bonifacio",
    "Calamba",
    "Clarin",
    "Concepcion",
    "Don Victoriano Chiongbian (Don Mariano Marcos)",
    "Jimenez",
    "Lopez Jaena",
    "Panaon",
    "Plaridel",
    "Sapang Dalaga",
    "Sinacaban",
    "Tudela",
  ];
}

class MisamisOriental {
  static List<String> citiesAndTowns = [
    "Cagayan de Oro City (Highly Urbanized)",
    "Gingoog City (Component City)",
    "Alubijid",
    "Balingasag",
    "Balingoan",
    "Binuangan",
    "Claveria",
    "El Salvador City (Component City)",
    "Gitagum",
    "Initao",
    "Jasaan",
    "Kinoguitan",
    "Lagonglong",
    "Laguindingan",
    "Libertad",
    "Lugait",
    "Magsaysay (Linugos)",
    "Manticao",
    "Medina",
    "Naawan",
    "Opol",
    "Salay",
    "Sugbongcogon",
    "Tagoloan",
    "Talisayan",
    "Villanueva",
  ];
}

class MountainProvince {
  static List<String> citiesAndTowns = [
    "Bontoc (Capital)",
    "Barlig",
    "Besao",
    "Bauko",
    "Natonin",
    "Paracelis",
    "Sabangan",
    "Sadanga",
    "Sagada",
    "Tadian",
  ];
}

class NegrosOccidental {
  static List<String> citiesAndTowns = [
    "Bacolod City (Highly Urbanized)",
    "Bago City (Component City)",
    "Cadiz City (Component City)",
    "Escalante City (Component City)",
    "Himamaylan City (Component City)",
    "Kabankalan City (Component City)",
    "La Carlota City (Component City)",
    "Sagay City (Component City)",
    "San Carlos City (Component City)",
    "Silay City (Component City)",
    "Sipalay City (Component City)",
    "Talisay City (Component City)",
    "Victorias City (Component City)",
    "Binalbagan",
    "Calatrava",
    "Candoni",
    "Cauayan",
    "Enrique B. Magalona (Saravia)",
    "Hinigaran",
    "Hinoba-an (Asia)",
    "Ilog",
    "Isabela",
    "La Castellana",
    "Manapla",
    "Moises Padilla (Magallon)",
    "Murcia",
    "Pontevedra",
    "Pulupandan",
    "Salvador Benedicto",
    "San Enrique",
    "Toboso",
    "Valladolid",
  ];
}

class NegrosOriental {
  static List<String> citiesAndTowns = [
    "Bais City (Component City)",
    "Bayawan City (Component City)",
    "Canlaon City (Component City)",
    "Dumaguete City (Highly Urbanized)",
    "Guihulngan City (Component City)",
    "Tanjay City (Component City)",
    "Amlan (Ayuquitan)",
    "Ayungon",
    "Bacong",
    "Basay",
    "Bindoy (Payabon)",
    "Dauin",
    "Jimalalud",
    "La Libertad",
    "Mabinay",
    "Manjuyod",
    "Pamplona",
    "San Jose",
    "Santa Catalina",
    "Siaton",
    "Sibulan",
    "Tayasan",
    "Valencia (Luzurriaga)",
    "Vallehermoso",
    "Zamboanguita",
  ];
}

class NorthernSamar {
  static List<String> citiesAndTowns = [
    "Catarman (Capital)",
    "Allen",
    "Biri",
    "Bobon",
    "Capul",
    "Catubig",
    "Gamay",
    "Laoang",
    "Lapinig",
    "Las Navas",
    "Lavezares",
    "Lope de Vega",
    "Mapanas",
    "Mondragon",
    "Palapag",
    "Pambujan",
    "Rosario",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Silvino Lobos",
    "Victoria",
  ];
}

class NuevaEcija {
  static List<String> citiesAndTowns = [
    "Palayan City (Capital) (Component City)",
    "Cabanatuan City (Highly Urbanized)",
    "Gapan City (Component City)",
    "Science City of Muñoz (Component City)",
    "San Jose City (Component City)",
    "Aliaga",
    "Bongabon",
    "Cabiao",
    "Carranglan",
    "Cuyapo",
    "Gabaldon (Bitulok & Sabani)",
    "General Mamerto Natividad",
    "General Tinio (Papaya)",
    "Guimba",
    "Jaen",
    "Laur",
    "Licab",
    "Llanera",
    "Lupao",
    "Nampicuan",
    "Pantabangan",
    "Peñaranda",
    "Quezon",
    "Rizal",
    "San Antonio",
    "San Isidro",
    "San Leonardo",
    "Santa Rosa",
    "Santo Domingo",
    "Talavera",
    "Talugtug",
    "Zaragoza",
  ];
}

class NuevaVizcaya {
  static List<String> citiesAndTowns = [
    "Bayombong (Capital)",
    "Alfonso Castañeda",
    "Ambaguio",
    "Aritao",
    "Bagabag",
    "Bambang",
    "Diadi",
    "Dupax del Norte",
    "Dupax del Sur",
    "Kasibu",
    "Kayapa",
    "Quezon",
    "Santa Fe",
    "Solano",
    "Villaverde (Ibung)",
  ];
}

class OccidentalMindoro {
  static List<String> citiesAndTowns = [
    "Mamburao (Capital)",
    "Abra de Ilog",
    "Calintaan",
    "Looc",
    "Lubang",
    "Magsaysay",
    "Paluan",
    "Rizal",
    "Sablayan",
    "San Jose",
    "Santa Cruz",
  ];
}

class OrientalMindoro {
  static List<String> citiesAndTowns = [
    "Calapan City (Highly Urbanized)",
    "Baco",
    "Bansud",
    "Bongabong",
    "Bulalacao (San Pedro)",
    "Gloria",
    "Mansalay",
    "Naujan",
    "Pinamalayan",
    "Pola",
    "Puerto Galera",
    "Roxas",
    "San Teodoro",
    "Socorro",
    "Victoria",
  ];
}
class Palawan {
  static List<String> citiesAndTowns = [
    "Puerto Princesa City (Highly Urbanized)",
    "Aborlan",
    "Agutaya",
    "Araceli",
    "Balabac",
    "Bataraza",
    "Brooke's Point",
    "Busuanga",
    "Cagayancillo",
    "Coron",
    "Culion",
    "Cuyo",
    "Dumaran",
    "El Nido (Bacuit)",
    "Kalayaan",
    "Linapacan",
    "Magsaysay",
    "Narra",
    "Quezon",
    "Rizal (Marcos)",
    "Roxas",
    "San Vicente",
    "Sofronio Española",
    "Taytay",
  ];
}


class ProvincesCities {
  static List<String> abraCities = [
    "Bangued",
    "Boliney",
    "Bucay",
    "Bucloc",
    "Daguioman",
    "Danglas",
    "Dolores",
    "La Paz",
    "Lacub",
    "Lagangilang",
    "Lagayan",
    "Langiden",
    "Licuan-Baay",
    "Luba",
    "Malibcong",
    "Manabo",
    "Penarrubia",
    "Pidigan",
    "Pilar",
    "Sallapadan",
    "San Isidro",
    "San Juan",
    "San Quintin",
    "Tayum",
    "Tineg",
    "Tubo",
    "Villaviciosa",
  ];

  static List<String> agusanDelNorteCities = [
    "Butuan City (Highly Urbanized)",
    "Buenavista",
    "Cabadbaran City (Component City)",
    "Carmen",
    "Jabonga",
    "Kitcharao",
    "Las Nieves",
    "Magallanes",
    "Nasipit",
    "Remedios T. Romualdez",
    "Santiago",
    "Tubay",
  ];

  static List<String> agusanDelSurCities = [
    "Bayugan City (Component City)",
    "Bunawan",
    "Esperanza",
    "La Paz",
    "Loreto",
    "Prosperidad (Capital)",
    "Rosario",
    "San Francisco (San Franz)",
    "San Luis",
    "Santa Josefa",
    "Sibagat",
    "Talacogon",
    "Trento",
    "Veruela",
  ];

  static List<String> aklanCities = [
    "Batan",
    "Buruanga",
    "Ibajay",
    "Kalibo (Capital)",
    "Lezo",
    "Libacao",
    "Madalag",
    "Makato",
    "Malay",
    "Malinao",
    "Nabas",
    "New Washington",
    "Numancia",
    "Tangalan",
  ];

  static List<String> albayCities = [
    "Legazpi City (Highly Urbanized)",
    "Ligao City (Component City)",
    "Tabaco City (Component City)",
    "Bacacay",
    "Camalig",
    "Daraga (Locsin)",
    "Guinobatan",
    "Jovellar",
    "Libon",
    "Malilipot",
    "Malinao",
    "Manito",
    "Oas",
    "Pio Duran",
    "Polangui",
    "Rapu-Rapu",
    "Santo Domingo (Libog)",
    "Tiwi",
  ];

  static List<String> antiqueCities = [
    "San Jose de Buenavista (Capital)",
    "Anini-y",
    "Barbaza",
    "Belison",
    "Bugasong",
    "Caluya",
    "Culasi",
    "Hamtic",
    "Laua-an",
    "Libertad",
    "Pandan",
    "Patnongon",
    "San Remigio",
    "Sebaste",
    "Sibalom",
    "Tibiao",
    "Tobias Fornier (Dao)",
    "Valderrama",
  ];

  static List<String> apayaoCities = [
    "Calanasan (Bayag)",
    "Conner (Poblacion)",
    "Flora (Poblacion)",
    "Kabugao (Capital)",
    "Luna (Poblacion)",
    "Pudtol (Poblacion)",
    "Santa Marcela (Poblacion)",
  ];

  static List<String> auroraCities = [
    "Baler (Capital)",
    "Casiguran",
    "Dilasag",
    "Dinalungan",
    "Dingalan",
    "Dipaculao",
    "Maria Aurora",
    "San Luis",
  ];

  static List<String> basilanCities = [
    "Isabela City (Capital) (Highly Urbanized)",
    "Akbar",
    "Al-Barka",
    "Hadji Mohammad Ajul",
    "Hadji Muhtamad",
    "Lamitan City (Component City)",
    "Lantawan",
    "Maluso",
    "Sumisip",
    "Tabuan-Lasa",
    "Tipo-Tipo",
    "Tuburan",
    "Ungkaya Pukan",
  ];

  static List<String> bataanCities = [
    "Balanga City (Component City)",
    "Abucay",
    "Bagac",
    "Dinalupihan",
    "Hermosa",
    "Limay",
    "Mariveles",
    "Morong",
    "Orani",
    "Orion",
    "Pilar",
    "Samal",
  ];

  static List<String> batangasCities = [
    "Batangas City (Capital) (Highly Urbanized)",
    "Lipa City (Highly Urbanized)",
    "Tanauan City (Component City)",
    "Agoncillo",
    "Alitagtag",
    "Balayan",
    "Balete",
    "Bauan",
    "Calaca",
    "Calatagan",
    "Cuenca",
    "Ibaan",
    "Laurel",
    "Lemery",
    "Lian",
    "Lobo",
    "Mabini",
    "Malvar",
    "Mataasnakahoy",
    "Nasugbu",
    "Padre Garcia",
    "Rosario",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Nicolas",
    "San Pascual",
    "Santa Teresita",
    "Santo Tomas",
    "Taal",
    "Talisay",
    "Taysan",
    "Tingloy",
    "Tuy",
  ];

  static List<String> benguetCities = [
    "Baguio City (Highly Urbanized)",
    "Atok",
    "Bakun",
    "Bokod",
    "Buguias",
    "Itogon",
    "Kabayan",
    "Kapangan",
    "Kibungan",
    "La Trinidad (Capital)",
    "Mankayan",
    "Sablan",
    "Tuba",
    "Tublay",
  ];

  static List<String> biliranCities = [
    "Naval (Capital)",
    "Almeria",
    "Biliran",
    "Cabucgayan",
    "Caibiran",
    "Culaba",
    "Kawayan",
    "Maripipi",
  ];

  static List<String> boholCities = [
    "Tagbilaran City (Component City)",
    "Alburquerque",
    "Alicia",
    "Anda",
    "Antequera",
    "Baclayon",
    "Balilihan",
    "Batuan",
    "Bien Unido",
    "Bilar",
    "Buenavista",
    "Calape",
    "Candijay",
    "Carmen",
    "Catigbian",
    "Clarin",
    "Corella",
    "Cortes",
    "Dagohoy",
    "Danao",
    "Dauis",
    "Dimiao",
    "Duero",
    "Garcia Hernandez",
    "Getafe",
    "Guindulman",
    "Inabanga",
    "Jagna",
    "Lila",
    "Loay",
    "Loboc",
    "Loon",
    "Mabini",
    "Maribojoc",
    "Panglao",
    "Pilar",
    "President Carlos P. Garcia",
    "Sagbayan",
    "San Isidro",
    "San Miguel",
    "Sevilla",
    "Sierra Bullones",
    "Sikatuna",
    "Talibon",
    "Trinidad",
    "Tubigon",
    "Ubay",
    "Valencia",
  ];

  static List<String> bukidnonCities = [
    "Malaybalay City (Highly Urbanized)",
    "Valencia City (Component City)",
    "Baungon",
    "Cabanglasan",
    "Damulog",
    "Dangcagan",
    "Don Carlos",
    "Impasugong",
    "Kadingilan",
    "Kalilangan",
    "Kibawe",
    "Kitaotao",
    "Lantapan",
    "Libona",
    "Malitbog",
    "Manolo Fortich",
    "Maramag",
    "Pangantucan",
    "Quezon",
    "San Fernando",
    "Sumilao",
    "Talakag",
  ];

  static List<String> bulacanCities = [
    "Malolos City (Capital) (Highly Urbanized)",
    "Meycauayan City (Component City)",
    "San Jose del Monte City (Component City)",
    "Angat",
    "Balagtas (Bigaa)",
    "Baliuag",
    "Bocaue",
    "Bulacan",
    "Bustos",
    "Calumpit",
    "Doña Remedios Trinidad",
    "Guiguinto",
    "Hagonoy",
    "Marilao",
    "Norzagaray",
    "Obando",
    "Pandi",
    "Paombong",
    "Plaridel",
    "Pulilan",
    "San Ildefonso",
    "San Miguel",
    "San Rafael",
    "Santa Maria",
  ];

  static List<String> cagayanCities = [
    "Tuguegarao City (Highly Urbanized)",
    "Abulug",
    "Alcala",
    "Allacapan",
    "Amulung",
    "Aparri",
    "Baggao",
    "Ballesteros",
    "Buguey",
    "Calayan",
    "Camalaniugan",
    "Claveria",
    "Enrile",
    "Gattaran",
    "Gonzaga",
    "Iguig",
    "Lal-lo",
    "Lasam",
    "Pamplona",
    "Peñablanca",
    "Piat",
    "Rizal",
    "Sanchez-Mira",
    "Santa Ana",
    "Santa Praxedes",
    "Santa Teresita",
    "Santa Ana",
    "Solana",
    "Tuao",
  ];

  static List<String> camarinesNorteCities = [
    "Daet (Capital) (Highly Urbanized)",
    "Basud",
    "Capalonga",
    "Labo",
    "Jose Panganiban",
    "Mercedes",
    "Paracale",
    "San Lorenzo Ruiz (Imelda)",
    "San Vicente",
    "Santa Elena",
    "Talisay",
    "Vinzons",
  ];

  static List<String> camarinesSurCities = [
    "Naga City (Highly Urbanized)",
    "Iriga City (Component City)",
    "Baao",
    "Balatan",
    "Bato",
    "Bombon",
    "Buhi",
    "Bula",
    "Cabusao",
    "Calabanga",
    "Camaligan",
    "Canaman",
    "Caramoan",
    "Del Gallego",
    "Gainza",
    "Garchitorena",
    "Goa",
    "Lagonoy",
    "Libmanan",
    "Lupi",
    "Magarao",
    "Milaor",
    "Minalabac",
    "Nabua",
    "Ocampo",
    "Pamplona",
    "Pasacao",
    "Pili (Capital)",
    "Presentacion (Parubcan)",
    "Ragay",
    "Sagñay",
    "San Fernando",
    "San Jose",
    "Sipocot",
    "Siruma",
    "Tigaon",
    "Tinambac",
  ];
}
