class SloveniaRegions {
  static List<String> Pomurska = [
    "Murska Sobota",
    "Lendava",
    "Gornja Radgona",
    "Ljutomer",
    "Beltinci",
    "Radenci",
    "Moravske Toplice",
    "Črenšovci",
    "Tišina",
    "Puconci",
    "Grad",
    "Velika Polana",
    "Dobrovnik",
    "Turnišče",
    "Križevci pri Ljutomeru",
    "Veržej",
    "Martjanci",
    "Gederovci",
    // Add more cities and towns as needed
  ];

  static List<String> Podravska = [
    "Maribor",
    "Ptuj",
    "Slovenj Gradec",
    "Slovenska Bistrica",
    "Dravograd",
    "Ormož",
    "Lenart",
    "Hoče–Slivnica",
    "Duplek",
    "Ruše",
    "Kidričevo",
    "Slovenske Konjice",
    "Pesnica",
    "Radlje ob Dravi",
    "Majšperk",
    "Markovci",
    "Benedikt",
    "Podlehnik",
    // Add more cities and towns as needed
  ];

  static List<String> Koroska = [
    "Ravne na Koroškem",
    "Slovenj Gradec",
    "Dravograd",
    "Mežica",
    "Radlje ob Dravi",
    "Prevalje",
    "Črna na Koroškem",
    "Podvelka",
    "Vuzenica",
    "Mislinja",
    "Vuhred",
    "Šentjanž",
    "Sele",
    "Ribnica na Pohorju",
    "Oplotnica",
    "Makole",
    // Add more cities and towns as needed
  ];

  // Define lists for other regions similarly

  static List<String> Savinjska = [
    "Celje",
    "Velenje",
    "Žalec",
    "Slovenske Konjice",
    "Laško",
    "Šentjur",
    "Šmarje pri Jelšah",
    "Rogaška Slatina",
    "Rogatec",
    "Vojnik",
    "Zreče",
    "Mozirje",
    "Vitanje",
    "Podčetrtek",
    "Prebold",
    "Braslovče",
    "Polzela",
    // Add more cities and towns as needed
  ];

  // Define lists for other regions similarly

  // Define lists for other regions similarly

  static List<String> ObalnoKraska = [
    "Koper",
    "Nova Gorica",
    "Piran",
    "Izola",
    "Ankaran",
    "Sežana",
    "Portorož",
    "Divača",
    "Lucija",
    "Postojna",
    "Ajdovščina",
    "Idrija",
    "Cerknica",
    "Ilirska Bistrica",
    "Vipava",
    "Komen",
    "Hrpelje-Kozina",
    "Miren-Kostanjevica",
    "Bovec",
    "Tolmin",
    "Kanal",
    "Brda",
    "Logatec",
    "Nova Gorica",
    "Ajdovščina",
    "Tolmin",
    "Šempeter-Vrtojba",
    "Renče-Vogrsko",
    "Miren-Kostanjevica",
    "Idrija",
    "Cerknica",
    "Ilirska Bistrica",
    "Vipava",
    "Logatec",
    "Pivka",
    "Vrhnika",
    "Loška Dolina",
    "Loški Potok",
    "Bloke",
    "Podbrdo",
    "Kobarid",
    "Kočevje",
    "Dutovlje",
    "Izola",
    "Sežana",
    "Postojna",
    "Ilirska Bistrica",
    "Nova Gorica",
    "Miren-Kostanjevica",
    "Sežana",
    "Hrpelje-Kozina",
    "Nova Gorica",
    "Komen",
    "Brda",
    "Idrija",
    "Bovec",
    "Ajdovščina",
    "Nova Gorica",
    "Tolmin",
    "Nova Gorica",
    "Idrija",
    "Vipava",
    "Šempeter-Vrtojba",
    "Miren-Kostanjevica",
    "Kobarid",
  ];

  static List<String> Gorenjska = [
    "Kranj",
    "Jesenice",
    "Škofja Loka",
    "Tržič",
    "Radovljica",
    "Železniki",
    "Cerklje na Gorenjskem",
    "Naklo",
    "Bohinjska Bistrica",
    "Šenčur",
    "Preddvor",
    "Zgornja Besnica",
    "Mengeš",
    "Zgornje Jezersko",
    "Gorje",
    "Žiri",
    // Add more cities and towns as needed
  ];

  static List<String> PrimorskoNotranjska = [
    "Postojna",
    "Ajdovščina",
    "Idrija",
    "Cerknica",
    "Ilirska Bistrica",
    "Vipava",
    "Logatec",
    "Pivka",
    "Vrhnika",
    "Loška Dolina",
    "Loški Potok",
    "Bloke",
    "Podbrdo",
    "Kobarid",
    "Tolmin",
    "Nova Gorica",
    "Bovec",
    // Add more cities and towns as needed
  ];

  static List<String> Goriska = [
    "Nova Gorica",
    "Ajdovščina",
    "Tolmin",
    "Šempeter-Vrtojba",
    "Renče-Vogrsko",
    "Miren-Kostanjevica",
    "Kanal",
    "Brda",
    "Bovec",
    "Kobarid",
    "Idrija",
    // Add more cities and towns as needed
  ];

  static List<String> Osrednjeslovenska = [
    "Ljubljana",
    "Domžale",
    "Kamnik",
    "Vrhnika",
    "Ig",
    "Škofljica",
    "Brezovica",
    "Log-Dragomer",
    "Lukovica",
    "Moravče",
    "Šmartno pri Litiji",
    "Trzin",
    "Dobrepolje",
    "Dol pri Ljubljani",
    "Grosuplje",
    "Ivančna Gorica",
    "Litija",
    "Lukovica",
    "Medvode",
    "Mengeš",
    "Mirna Peč",
    "Trbovlje",
    "Velike Lašče",
    "Vodice",
    "Vrhnika",
    // Add more cities and towns as needed
  ];

  static List<String> JugovzhodnaSlovenija = [
    "Novo Mesto",
    "Črnomelj",
    "Trebnje",
    "Šentjernej",
    "Škocjan",
    "Šmarješke Toplice",
    "Žužemberk",
    "Mirna",
    "Dolenjske Toplice",
    "Metlika",
    "Semič",
    "Kostanjevica na Krki",
    "Krško",
    "Sevnica",
    "Brežice",
    "Kočevje",
    "Osilnica",
    "Kočevska Reka",
    "Ribnica",
    // Add more cities and towns as needed
  ];

  static List<String> NotranjskoKraska = [
    "Cerknica",
    "Ilirska Bistrica",
    "Loška Dolina",
    "Pivka",
    "Postojna",
    "Bloke",
    "Borovnica",
    "Kočevje",
    "Vrhnika",
    "Sodražica",
    "Ribnica",
    "Idrija",
    "Nova Gorica",
    "Ajdovščina",
    "Tolmin",
    "Šempeter-Vrtojba",
    "Renče-Vogrsko",
    "Miren-Kostanjevica",
    "Kanal",
    "Brda",
    "Bovec",
    "Kobarid",
    "Municipality of Cerklje na Gorenjskem",
    "Municipality of Dobrepolje",
    "Municipality of Dobrova-Polhov Gradec",
    "Municipality of Dol pri Ljubljani",
    "Municipality of Domžale",
    "Municipality of Grosuplje",
    "Municipality of Horjul",
    "Municipality of Ig",
    "Municipality of Ivančna Gorica",
    "Municipality of Kamnik",
    "Municipality of Komenda",
    "Municipality of Litija",
    "Municipality of Ljubljana",
    "Municipality of Logatec",
    "Municipality of Lukovica",
    "Municipality of Medvode",
    "Municipality of Mengeš",
    "Municipality of Moravče",
    "Municipality of Škofljica",
    "Municipality of Šmartno pri Litiji",
    "Municipality of Trzin",
    "Municipality of Velike Lašče",
    "Municipality of Vodice",
    "Municipality of Vrhnika",
    // Add more cities and towns as needed
  ];


  // Previous lists here...

  static List<String> Zasavska = [
  "Trbovlje",
  "Hrastnik",
  "Zagorje ob Savi",
  "Litija",
  "Šmartno pri Litiji",
  "Trencin",
  "Kisovec",
  "Dol pri Hrastniku",
  "Radeče",
  "Zagorje ob Savi",
  "Hrastnik",
  "Trbovlje",
  // Add more cities and towns as needed
  ];

  static List<String> Posavska = [
  "Brežice",
  "Krško",
  "Sevnica",
  "Radeče",
  "Bistrica ob Sotli",
  "Kostanjevica na Krki",
  "Radeče",
  "Sevnica",
  ];


  }
