class SavanesRegion {
  static List<String> neighborhoods = [
    "Mango",
    "Dapaong",
    "Bassar",
    "Kara",
    "Niamtougou",
    "Pagouda",
    "Kande",
    "Tandjouaré",
    "Bafilo",
    "Cinkassé",
    "Sarakawa",
    "Mandouri",
    "Nadianga",
    "Sanda-Kara",
    "Bandjeli",
    "Binaparba",
    "Wuro",
    "Dimouri",
    "Mélia",
    "Sadori",
    "Tcharé",
    "Tchitchao",
    "Kpendjal",
    "Manda",
    "Ogaro",
    "Koundjali",
    "Kpendjal",
    "Koroma",
    "Tandjoare",
    "Wéré",
    "Yaka",
  ];
}

class KaraRegion {
  static List<String> neighborhoods = [
    "Kara (Capital)",
    "Kéran",
    "Doufelgou",
    "Kozah",
    "Assoli",
    "Blitta",
    "Notse",
    "Anié",
    "Kpalimé",
    "Notsé",
    "Notokondi",
    "Kévé",
    "Koliakopé",
    "Bassadji",
    "Kowagbe",
    "Kpélé",
    "Binah",
    "Nadjounda",
    "Kiwi",
    "Katchamba",
    "Kabou",
    "Bafilo",
    "Kévé",
    "Niamtougou",
    "Gando",
    "Kéran",
    "Kouarfa",
    "Nadjoundou",
    "Pendjari",
  ];
}

class CentraleRegion {
  static List<String> neighborhoods = [
    "Sokodé (Capital)",
    "Atakpamé",
    "Bafilo",
    "Sotouboua",
    "Tchamba",
    "Bassar",
    "Niamtougou",
    "Badou",
    "Pagouda",
    "Lama-Kara",
    "Bassar",
    "Wawa",
    "Niamtougou",
    "Aouda",
    "Bitchabé",
    "Yoto",
    "Kpélé",
    "Notsé",
    "Vogan",
    "Anié",
  ];
}

class PlateauxRegion {
  static List<String> neighborhoods = [
    "Atakpamé (Capital)",
    "Badou",
    "Kpalimé",
    "Notsé",
    "Tchamba",
    "Sotouboua",
    "Anié",
    "Bassar",
    "Blitta",
    "Bafilo",
    "Kédia",
    "Tokpli",
    "Kagbladji",
    "Koriko",
    "Notsé",
    "Kpélé",
    "Kanyikopé",
    "Kadi",
    "Kovié",
    "Takpamba",
    "Kovié",
    "Kétou",
    "Kadokondji",
    "Attitogon",
    "Tové",
    "Afadé",
    "Koussountou",
    "Kamina",
    "Kpélé",
  ];
}

class MaritimeRegion {
  static List<String> neighborhoods = [
    "Lomé (Capital)",
    "Tsevie",
    "Tsévié",
    "Aného",
    "Kpélé",
    "Notsé",
    "Vogan",
    "Togoville",
    "Adéta-Kpodji",
    "Agbodrafo",
    "Ahépé",
    "Afagnan",
    "Aflao",
    "Tabligbo",
    "Keta",
    "Glidji",
  ];
}
