class Tobago {
  static List<String> neighborhoods = [
    "Scarborough",
    "Crown Point",
    "Roxborough",
    "Charlotteville",
    "Speyside",
    "Plymouth",
    "Moriah",
    "Castara",
    "Bloody Bay",
    "Parlatuvier",
    "Belle Garden",
    "Goodwood",
    "Black Rock",
    "Mason Hall",
    "Lambeau",
    "Les Coteaux",
    "Lowlands",
    "Bacolet",
    "Mount St. George",
    "Friendship",
    "Golden Lane",
  ];
}

class EasternTrinidad {
  static List<String> neighborhoods = [
    "Sangre Grande",
    "Manzanilla",
    "Toco",
    "Matelot",
    "Valencia",
    "Grande Riviere",
    "Cumana",
    "Guaico",
    "Matura",
    "Balandra",
    "Valencia Junction",
    "Lopinot Village",
    "Cumuto",
    "Valencia Old Road",
    "Fishing Pond",
    "Cunaripo",
    "Tableland",
    "Plum Mitan Village",
    "Grande Cache",
    "Sangre Chiquito",
    "Plum Road Village",
  ];
}
class NorthEastTrinidad {
  static List<String> neighborhoods = [
    "Arima",
    "Blanchisseuse",
    "Arouca",
    "Curepe",
    "Lopinot",
    "Santa Cruz",
    "Maracas",
    "La Horquetta",
    "D'Abadie",
    "Maloney",
    "Blanchisseuse Village",
    "Caura",
    "Arima Old Road",
    "Cleaver Road",
    "La Retreat Estate",
    "Brasso Seco Village",
    "Cumaca",
    "San Juan",
    "El Dorado",
    "St. Joseph",
    "Tacarigua",
  ];
}

class Arima {
  static List<String> neighborhoods = [
    "Arima",
    "Malabar",
    "O'Meara",
    "Cleaver Woods",
    "Calvary Hill",
    "La Retreat",
    "Wallerfield",
    "Demerara",
    "La Finette",
    "Oropune",
    "Calvary Hill",
    "Bon Air",
    "Eden Gardens",
    "Beetham Gardens",
    "La Horquetta",
    "Mt. Hope",
    "Piarco",
    "Carapo",
    "Petit Bourg",
    "Lopinot",
  ];
}

class PortOfSpain {
  static List<String> neighborhoods = [
    "Port of Spain",
    "St. James",
    "Woodbrook",
    "Belmont",
    "Laventille",
    "Cocorite",
    "Cascade",
    "Maraval",
    "Barataria",
    "St. Clair",
    "Gonzales",
    "Morvant",
    "Woodbrook",
    "Laventille",
    "Mucurapo",
    "St. Ann's",
    "Woodford Square",
    "Newtown",
    "Newtown Playboys",
    "Success Village",
    "Malick",
  ];
}
class Chaguanas {
  static List<String> neighborhoods = [
    "Chaguanas",
    "Montrose",
    "Enterprise",
    "Cunupia",
    "Felicity",
    "Endeavour",
    "Charlieville",
    "Munroe Road",
    "Longdenville",
    "Caroni",
    "Carapichaima",
    "Freeport",
    "Chase Village",
    "St. Helena",
    "Chin Chin",
    "Caparo",
    "Edinburgh 500",
    "Esperanza",
    "Madras Settlement",
    "St. Thomas Village",
    "Felicity Village",
  ];
}

class CouvaTabaquiteTalparo {
  static List<String> neighborhoods = [
    "Couva",
    "Claxton Bay",
    "Balmain",
    "Tabaquite",
    "California",
    "Gasparillo",
    "St. Mary's",
    "Carapichaima",
    "Freeport",
    "Felicity",
    "Ste. Madeleine",
    "Barrackpore",
    "Palmiste",
    "Piarco Village",
    "Mc Bean",
    "Hermitage",
    "Dow Village",
    "Waterloo",
    "Spring Village",
    "Gran Couva",
    "Indian Trail",
  ];
}

class DiegoMartin {
  static List<String> neighborhoods = [
    "Diego Martin",
    "Petit Valley",
    "Carenage",
    "Westmoorings",
    "Glencoe",
    "Diamond Vale",
    "Blue Range",
    "Goodwood Park",
    "Bagatelle",
    "Petit Valley",
    "Cocorite",
    "Morne Coco Road",
    "Covigne Road",
    "La Puerta",
    "Chaguaramas",
    "Four Roads",
    "La Sagesse",
    "River Estate",
    "Fairways",
  ];
}

class MayaroRioClaro {
  static List<String> neighborhoods = [
    "Rio Claro",
    "Mayaro",
    "Guayaguayare",
    "Tableland",
    "New Grant",
    "Poole",
    "Plum Mitan",
    "Ecclesville",
    "Biche",
    "Mafeking",
    "Guayaguayare",
    "Eccles Village",
    "Mafeking Village",
    "Gran Couva",
    "Gran Maturin",
    "Lengua",
    "Mendez Village",
    "Ortoire Village",
    "St. Julien",
    "Cedar Grove",
    "Lengua Village",
  ];
}

class PenalDebe {
  static List<String> neighborhoods = [
    "Penal",
    "Debe",
    "San Francique",
    "Clarke Road",
    "Penal Rock Road",
    "Rochard Douglas Road",
    "Debe Trace",
    "Lachoos Road",
    "Suchit Trace",
    "Wilson Road",
    "Barrackpore",
    "Caparo",
    "Clarke Road Village",
    "Penal Rock Road Village",
    "Monkey Town",
    "Plaisance Park",
    "Siparia Old Road",
    "Rochard Road",
    "Union Village",
    "Lengua Road",
  ];
}


