class WallisAndFutuna {
  static List<String> hihifoDistrict = [
    "Mata-Utu",
    "Falaleu",
    "Haafuasia",
    "Aka'aka",
    "Aka'aka Nofo",
    "Akavaina",
    "Alele",
    "Gahi",
    "Kolia",
    "Kolopelu",
    "Mala'e",
    "Mala'e Hihifo",
    "Mala'efo'ou",
    "Motu Uta",
    "Motuloa",
    "Utufua",
  ];

  static List<String> hahakeDistrict = [
    "Vaitupu",
    "Alele",
    "Lano",
    "Mu'a",
    "Akoteu",
    "Aka'aka",
    "Aka'aka Nofo",
    "Akavaina",
    "Akelata",
    "Lavegahau",
    "Liku",
    "Liku Nofo",
    "Logologo",
    "Mala'e",
    "Mala'e Hahake",
    "Motopu",
    "Teesi",
    "Tevutuanai",
    "Utufua",
  ];

  static List<String> sigaveDistrict = [
    "Sigave",
    "Leava",
    "Gahi",
    "Fiua",
    "Akavaina",
    "Leava Nofo",
    "Mata'utu",
    "Nuku",
    "Tufuone",
    "Vaitupu",
    "Vaimalau",
    "Vailala",
    "Falea",
    "Falehau",
    "Falehau (Mala'e)",
    "Falaise",
    "Faua",
    "Fugalei",
    "Lavegahau",
  ];
}
